// Affinity GBA Runtime — Mode 7 floor with D-pad camera + OAM sprites
// Built with devkitARM + libtonc

#include <tonc.h>
#include <string.h>

// ---------------------------------------------------------------------------
// Map data — generated by editor, or fallback checkerboard
// ---------------------------------------------------------------------------

#include "mapdata.h"

// ---------------------------------------------------------------------------
// Mode 7 state
// ---------------------------------------------------------------------------

// Camera (16.8 fixed-point for position, angle in brads)
static FIXED cam_x;
static FIXED cam_z;
static FIXED cam_h;        // height above floor
static u16   cam_angle;    // brad angle
static FIXED cam_fov;      // focal distance D

// Precomputed sin/cos for current angle
static FIXED g_cosf, g_sinf;

// Horizon scanline — variable for pitch control (A/B buttons)
static int m7_horizon = 54;

// ---------------------------------------------------------------------------
// Floor sprites — positions in 16.8 fixed-point
// ---------------------------------------------------------------------------

#define MAX_FLOOR_SPRITES 16

typedef struct {
    FIXED x;
    FIXED y;         // height above floor (16.8)
    FIXED z;
    u16   palIdx;    // OBJ palette color index
} FloorSpriteGBA;

static FloorSpriteGBA g_sprites[MAX_FLOOR_SPRITES];
static int g_spriteCount = 0;

// Sprite projection result for sorting
typedef struct {
    int screenX;
    int screenY;
    int scale;    // 8.8 fixed-point scale (256 = 1x)
    int depth;    // for sorting (larger = farther)
    int idx;      // sprite index
} SpriteProjGBA;

// ---------------------------------------------------------------------------
// Mode 7 HBlank interrupt — per-scanline affine update
// ---------------------------------------------------------------------------

static void m7_hbl(void)
{
    int vc = REG_VCOUNT;

    // Above horizon: disable BG2 so backdrop color (sky) shows
    if (vc < m7_horizon)
    {
        REG_DISPCNT &= ~DCNT_BG2;
        return;
    }
    if (vc >= SCREEN_HEIGHT)
        return;

    // Re-enable BG2 at horizon
    REG_DISPCNT |= DCNT_BG2;

    // lambda = cam_height / (scanline - horizon)
    FIXED lam = cam_h * lu_div(vc - m7_horizon) >> 12;

    FIXED lcf = lam * g_cosf >> 8;
    FIXED lsf = lam * g_sinf >> 8;

    // Affine matrix — only PA and PC matter for per-scanline Mode 7
    REG_BG2PA =  lcf >> 4;
    REG_BG2PB = 0;
    REG_BG2PC =  lsf >> 4;
    REG_BG2PD = 0;

    // Reference point
    FIXED lxr, lyr;

    lxr = 120 * (lcf >> 4);
    lyr = cam_fov * (lsf >> 4);
    REG_BG2X = cam_x - lxr + lyr;

    lxr = 120 * (lsf >> 4);
    lyr = cam_fov * (lcf >> 4);
    REG_BG2Y = cam_z - lxr - lyr;
}

// ---------------------------------------------------------------------------
// Build checkerboard tiles + tilemap
// ---------------------------------------------------------------------------

static void load_checkerboard(void)
{
    // Affine BGs use 8bpp tiles: 1 byte per pixel, 64 bytes per 8x8 tile
    // Tile 0: palette index 1 (dark green)
    memset(&tile8_mem[2][0], 1, 64);
    // Tile 1: palette index 2 (light green)
    memset(&tile8_mem[2][1], 2, 64);

    // Set palette colors (8bpp uses single 256-color palette)
    pal_bg_mem[0] = RGB15(10, 16, 24);  // backdrop = sky blue
    pal_bg_mem[1] = RGB15(4, 10, 4);    // dark green
    pal_bg_mem[2] = RGB15(8, 18, 8);    // light green

    // Affine tilemap: 8-bit entries (just tile index, no flip/palette bits)
    u8 *map = (u8*)se_mem[28];
    for (int y = 0; y < 32; y++)
    {
        for (int x = 0; x < 32; x++)
        {
            int check = ((x / 4) + (y / 4)) & 1;
            map[y * 32 + x] = check ? 1 : 0;
        }
    }
}

#ifdef AFFINITY_HAS_MAPDATA
static void load_editor_map(void)
{
    memcpy(&tile8_mem[2][0], afn_tiles, afn_tilesLen);
    memcpy(pal_bg_mem, afn_palette, afn_paletteLen);
    u8 *map = (u8*)se_mem[28];
    memcpy(map, afn_tilemap, afn_tilemapLen);
}
#endif

// ---------------------------------------------------------------------------
// OBJ sprite setup — 8x8 diamond shape in OBJ VRAM
// ---------------------------------------------------------------------------

static void init_obj_sprites(void)
{
    // Enable OBJ layer and 1D OBJ mapping
    REG_DISPCNT |= DCNT_OBJ | DCNT_OBJ_1D;

    // Tile 0: solid 8x8 square (placeholder until sprite editor)
    {
        u32 *t0 = (u32*)&tile_mem[4][0];
        int k;
        for (k = 0; k < 8; k++) t0[k] = 0x11111111;
    }

    // Tile 16: small 2x2 dot for minimap icons
    {
        u32 *dot = (u32*)&tile_mem[4][16];
        int k;
        for (k = 0; k < 8; k++) dot[k] = 0;
        dot[0] = 0x00000011;
        dot[1] = 0x00000011;
    }

    // Set OBJ palette banks — each bank has its color at index 1
    // (the diamond tile uses palette index 1 for filled pixels)
    // Bank 0: default yellow
    pal_obj_mem[0*16 + 0] = 0;
    pal_obj_mem[0*16 + 1] = RGB15(31, 31, 0);
    // Bank 1: yellow
    pal_obj_mem[1*16 + 0] = 0;
    pal_obj_mem[1*16 + 1] = RGB15(31, 31, 0);
    // Bank 2: red
    pal_obj_mem[2*16 + 0] = 0;
    pal_obj_mem[2*16 + 1] = RGB15(31, 8, 8);
    // Bank 3: blue
    pal_obj_mem[3*16 + 0] = 0;
    pal_obj_mem[3*16 + 1] = RGB15(8, 8, 31);
    // Bank 4: green
    pal_obj_mem[4*16 + 0] = 0;
    pal_obj_mem[4*16 + 1] = RGB15(8, 31, 8);
    // Bank 5: pink
    pal_obj_mem[5*16 + 0] = 0;
    pal_obj_mem[5*16 + 1] = RGB15(31, 16, 31);
    // Bank 6: white (for minimap dots)
    pal_obj_mem[6*16 + 0] = 0;
    pal_obj_mem[6*16 + 1] = RGB15(31, 31, 31);
    pal_obj_mem[6*16 + 2] = RGB15(20, 20, 20);
    pal_obj_mem[6*16 + 3] = RGB15(31, 0, 0);

    // Hide all OBJ initially
    oam_init(obj_mem, 128);
}

// Place demo sprites if no editor data
static void init_demo_sprites(void)
{
    // Place a few sprites around the map for testing
    g_sprites[0].x = 160 << 8;
    g_sprites[0].y = 0;
    g_sprites[0].z = 128 << 8;
    g_sprites[0].palIdx = 1;

    g_sprites[1].x = 96 << 8;
    g_sprites[1].y = 10 << 8;   // floating
    g_sprites[1].z = 96 << 8;
    g_sprites[1].palIdx = 2;

    g_sprites[2].x = 160 << 8;
    g_sprites[2].y = 0;
    g_sprites[2].z = 64 << 8;
    g_sprites[2].palIdx = 3;

    g_sprites[3].x = 64 << 8;
    g_sprites[3].y = 20 << 8;   // high up
    g_sprites[3].z = 160 << 8;
    g_sprites[3].palIdx = 4;

    g_spriteCount = 4;
}

#ifdef AFFINITY_HAS_SPRITES
#if AFN_SPRITE_COUNT > 0
static void load_editor_sprites(void)
{
    int i;
    int count = AFN_SPRITE_COUNT;
    if (count > MAX_FLOOR_SPRITES) count = MAX_FLOOR_SPRITES;

    for (i = 0; i < count; i++)
    {
        g_sprites[i].x      = afn_sprite_data[i][0];
        g_sprites[i].y      = afn_sprite_data[i][1];
        g_sprites[i].z      = afn_sprite_data[i][2];
        g_sprites[i].palIdx = afn_sprite_data[i][3];
    }
    g_spriteCount = count;
}
#endif
#endif

// ---------------------------------------------------------------------------
// Project sprites to screen and update OAM
// ---------------------------------------------------------------------------

static void update_sprites(void)
{
    SpriteProjGBA proj[MAX_FLOOR_SPRITES];
    int projCount = 0;
    int i, j;
    SpriteProjGBA tmp;

    for (i = 0; i < g_spriteCount; i++)
    {
        // Vector from camera to sprite (in fixed-point)
        FIXED dx = g_sprites[i].x - cam_x;
        FIXED dz = g_sprites[i].z - cam_z;

        // Camera-space projection:
        // depth = dx*sinA - dz*cosA  (along view axis, positive = in front)
        // side  = dx*cosA + dz*sinA  (perpendicular, positive = right)
        FIXED fovLambda = (dx * g_sinf - dz * g_cosf) >> 8;
        FIXED side      = (dx * g_cosf + dz * g_sinf) >> 8;

        // Skip if behind camera
        if (fovLambda <= 64) continue;

        // Perspective projection using cam_fov as focal distance
        FIXED heightDiff = cam_h - g_sprites[i].y;
        int screenY = m7_horizon + (int)((heightDiff * cam_fov) / fovLambda);
        int screenX = 120 + (int)((side * cam_fov) / fovLambda);

        // Scale for sizing (larger = closer/bigger)
        int scale = (int)((cam_h * cam_fov) / fovLambda);

        // Skip if off-screen
        if (screenY < -16 || screenY > 168) continue;
        if (screenX < -32 || screenX > 272) continue;
        if (scale < 1) continue;

        proj[projCount].screenX = screenX;
        proj[projCount].screenY = screenY;
        proj[projCount].scale   = scale;
        proj[projCount].depth   = fovLambda;
        proj[projCount].idx     = i;
        projCount++;
    }

    // Simple bubble sort front-to-back (closest first gets lowest OAM index = drawn on top)
    for (i = 0; i < projCount - 1; i++)
        for (j = i + 1; j < projCount; j++)
            if (proj[i].depth > proj[j].depth)
            {
                tmp = proj[i];
                proj[i] = proj[j];
                proj[j] = tmp;
            }

    // Render projected sprites as non-affine 8x8 OBJ (slots 16+)
    for (i = 0; i < projCount && i < 16; i++)
    {
        int oamIdx = 16 + i;
        int sx = proj[i].screenX - 4;  // center 8x8 sprite
        int sy = proj[i].screenY - 4;

        int palBank = g_sprites[proj[i].idx].palIdx;
        if (palBank > 5) palBank = 1;

        obj_mem[oamIdx].attr0 = ATTR0_Y(sy & 0xFF) | ATTR0_SQUARE;
        obj_mem[oamIdx].attr1 = ATTR1_X(sx & 0x1FF) | ATTR1_SIZE_8;
        obj_mem[oamIdx].attr2 = ATTR2_ID(0) | ATTR2_PRIO(0) | ATTR2_PALBANK(palBank);
    }

    // Hide remaining floor sprite OBJ slots
    for (; i < 16; i++)
    {
        obj_mem[16 + i].attr0 = ATTR0_HIDE;
    }
}

// ---------------------------------------------------------------------------
// Minimap — 32x32 pixel grid at bottom-left using BG0 (text mode)
// ---------------------------------------------------------------------------

#define MINIMAP_X  4     // screen position (pixels from left)
#define MINIMAP_Y  124   // screen position (pixels from bottom area)
#define MINIMAP_W  32    // minimap width in pixels (= 4 tiles)
#define MINIMAP_H  32    // minimap height in pixels (= 4 tiles)

// Tile indices in charblock 0 for minimap
#define TILE_MINIMAP_BG    1   // dark background tile
#define TILE_MINIMAP_GRID  2   // grid line tile (lighter)
#define TILE_MINIMAP_CAM   3   // camera dot (bright)

static void init_minimap(void)
{
    // BG0: charblock 0, screenblock 30, text mode, priority 0 (on top)
    REG_BG0CNT = BG_CBB(0) | BG_SBB(30) | BG_4BPP | BG_REG_32x32 | BG_PRIO(0);

    // BG palette for minimap (palette bank 1, indices 16-31)
    pal_bg_mem[16 + 0] = 0;                    // transparent
    pal_bg_mem[16 + 1] = RGB15(2, 4, 2);       // dark green (minimap bg)
    pal_bg_mem[16 + 2] = RGB15(5, 10, 5);      // lighter green (grid lines)
    pal_bg_mem[16 + 3] = RGB15(31, 31, 31);    // white (camera dot)

    // Build tiles in charblock 0
    // Tile 0: already empty (transparent)

    // Tile 1: solid dark background (all pixels = palette index 1)
    {
        u32 *t = (u32*)&tile_mem[0][TILE_MINIMAP_BG];
        int k;
        for (k = 0; k < 8; k++)
            t[k] = 0x11111111;  // 4bpp: each nibble = palette idx 1
    }

    // Tile 2: grid tile — border pixels are brighter
    {
        u32 *t = (u32*)&tile_mem[0][TILE_MINIMAP_GRID];
        int k;
        // Row 0: all grid color (top border)
        t[0] = 0x22222222;
        // Rows 1-6: left pixel grid, rest dark
        for (k = 1; k < 7; k++)
            t[k] = 0x11111112;  // leftmost pixel = 2, rest = 1
        // Row 7: all grid color (bottom border)
        t[7] = 0x22222222;
    }

    // Clear BG0 screenblock 30 (all transparent)
    {
        u16 *map = (u16*)se_mem[30];
        int k;
        for (k = 0; k < 32*32; k++)
            map[k] = 0;
    }

    // Fill the minimap area (4x4 tiles starting at tile coords for bottom-left)
    // BG0 scroll will position it. We draw at tile (0,0) to (3,3) and scroll BG0.
    {
        u16 *map = (u16*)se_mem[30];
        int tx, ty;
        for (ty = 0; ty < 4; ty++)
        {
            for (tx = 0; tx < 4; tx++)
            {
                // Use grid tile (has border lines)
                map[ty * 32 + tx] = TILE_MINIMAP_GRID | SE_PALBANK(1);
            }
        }
    }

    // Scroll BG0 so tile (0,0) appears at screen position (MINIMAP_X, MINIMAP_Y)
    // BG scroll is unsigned 9-bit wrapping, so -N = 512-N
    REG_BG0HOFS = (512 - MINIMAP_X) & 0x1FF;
    REG_BG0VOFS = (512 - MINIMAP_Y) & 0x1FF;
}

// Update minimap OBJ sprites (camera + floor sprites) using OBJ slots 0-15
static void update_minimap(void)
{
    int i;
    int oamIdx = 0;

    // Camera position dot — OBJ slot 0
    // Map 256x256 tile world to 32x32 minimap pixels
    // cam_x/cam_z are 16.8 fixed, so >> 8 gives pixel, then >> 3 gives minimap pos
    int camMX = MINIMAP_X + ((cam_x >> 8) >> 3);  // 256px map / 8 = 32px minimap
    int camMY = MINIMAP_Y + ((cam_z >> 8) >> 3);

    // Clamp to minimap bounds
    if (camMX < MINIMAP_X) camMX = MINIMAP_X;
    if (camMX > MINIMAP_X + MINIMAP_W - 1) camMX = MINIMAP_X + MINIMAP_W - 1;
    if (camMY < MINIMAP_Y) camMY = MINIMAP_Y;
    if (camMY > MINIMAP_Y + MINIMAP_H - 1) camMY = MINIMAP_Y + MINIMAP_H - 1;

    // Use tile 1 (2x2 dot) with palette bank 6 (white) for camera, no affine
    obj_mem[oamIdx].attr0 = ATTR0_Y(camMY & 0xFF) | ATTR0_SQUARE;
    obj_mem[oamIdx].attr1 = ATTR1_X(camMX & 0x1FF) | ATTR1_SIZE_8;
    obj_mem[oamIdx].attr2 = ATTR2_ID(16) | ATTR2_PRIO(0) | ATTR2_PALBANK(6);
    oamIdx++;

    // Sprite dots on minimap
    for (i = 0; i < g_spriteCount && oamIdx < 16; i++)
    {
        int smx = MINIMAP_X + ((g_sprites[i].x >> 8) >> 3);
        int smy = MINIMAP_Y + ((g_sprites[i].z >> 8) >> 3);

        // Skip if outside minimap
        if (smx < MINIMAP_X || smx > MINIMAP_X + MINIMAP_W - 1) continue;
        if (smy < MINIMAP_Y || smy > MINIMAP_Y + MINIMAP_H - 1) continue;

        int palBank = g_sprites[i].palIdx;
        if (palBank > 5) palBank = 1;

        obj_mem[oamIdx].attr0 = ATTR0_Y(smy & 0xFF) | ATTR0_SQUARE;
        obj_mem[oamIdx].attr1 = ATTR1_X(smx & 0x1FF) | ATTR1_SIZE_8;
        obj_mem[oamIdx].attr2 = ATTR2_ID(16) | ATTR2_PRIO(0) | ATTR2_PALBANK(palBank);
        oamIdx++;
    }

    // Hide remaining minimap OBJ slots
    for (; oamIdx < 16; oamIdx++)
    {
        obj_mem[oamIdx].attr0 = ATTR0_HIDE;
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

int main(void)
{
    // --- Video setup ---
    // Mode 1: BG0/BG1 = text, BG2 = affine (rotation/scaling)
    REG_DISPCNT = DCNT_MODE1 | DCNT_BG0 | DCNT_BG2;

    // BG2: charblock 2, screenblock 28, 32x32 affine map, 8bpp tiles, wrap
    REG_BG2CNT = BG_CBB(2) | BG_SBB(28) | BG_AFF_32x32 | BG_8BPP | BG_WRAP;

    // Identity affine (overwritten by HBlank each scanline)
    REG_BG2PA = 0x0100;
    REG_BG2PB = 0;
    REG_BG2PC = 0;
    REG_BG2PD = 0x0100;
    REG_BG2X  = 0;
    REG_BG2Y  = 0;

    // --- Load map data ---
#ifdef AFFINITY_HAS_MAPDATA
    load_editor_map();
#else
    load_checkerboard();
#endif

    // --- OBJ sprite setup ---
    init_obj_sprites();

    // --- Minimap setup ---
    init_minimap();

#if defined(AFFINITY_HAS_SPRITES) && AFN_SPRITE_COUNT > 0
    load_editor_sprites();
#else
    #ifndef AFFINITY_HAS_MAPDATA
    init_demo_sprites();
    #endif
#endif

    // --- Camera init ---
#ifdef AFFINITY_HAS_SPRITES
    cam_x     = AFN_CAM_X;
    cam_z     = AFN_CAM_Z;
    cam_h     = AFN_CAM_H;
    cam_angle = AFN_CAM_ANGLE;
    cam_fov   = 128;
    m7_horizon = AFN_CAM_HORIZON;
#else
    cam_x     = 128 << 8;
    cam_z     = 128 << 8;
    cam_h     = 64 << 8;
    cam_angle = 0;
    cam_fov   = 128;
#endif

    // Precompute initial sin/cos
    g_cosf = lu_cos(cam_angle) >> 4;
    g_sinf = lu_sin(cam_angle) >> 4;

    // --- Set up HBlank interrupt ---
    irq_init(NULL);
    irq_add(II_VBLANK, NULL);    // needed for VBlankIntrWait()
    irq_add(II_HBLANK, m7_hbl);

    // --- Main loop ---
    while (1)
    {
        VBlankIntrWait();
        // Disable BG2 at start of frame so scanlines above horizon show sky
        REG_DISPCNT &= ~DCNT_BG2;
        key_poll();

        FIXED moveSpeed = 37;    // ~35 editor units/s → 8.75 GBA px/s at 60fps
        int   rotSpeed  = 0x0200;

        // Rotate
        if (key_is_down(KEY_LEFT))
            cam_angle -= rotSpeed;
        if (key_is_down(KEY_RIGHT))
            cam_angle += rotSpeed;

        // Update sin/cos
        g_cosf = lu_cos(cam_angle) >> 4;
        g_sinf = lu_sin(cam_angle) >> 4;

        // Move forward/back
        if (key_is_down(KEY_UP))
        {
            cam_x += (g_sinf * moveSpeed) >> 8;
            cam_z -= (g_cosf * moveSpeed) >> 8;
        }
        if (key_is_down(KEY_DOWN))
        {
            cam_x -= (g_sinf * moveSpeed) >> 8;
            cam_z += (g_cosf * moveSpeed) >> 8;
        }

        // Height (L/R shoulders) — matches editor Q/E speed
        if (key_is_down(KEY_L) && cam_h > (16 << 8))
            cam_h -= 85;
        if (key_is_down(KEY_R) && cam_h < (200 << 8))
            cam_h += 85;

        // Pitch / orbit (A = look down, B = look up)
        if (key_is_down(KEY_A) && m7_horizon < 120)
            m7_horizon += 2;
        if (key_is_down(KEY_B) && m7_horizon > 10)
            m7_horizon -= 2;

        // Clamp camera to map bounds (256x256 map, 16.8 fixed-point)
        if (cam_x < 0) cam_x = 0;
        if (cam_x > (256 << 8)) cam_x = 256 << 8;
        if (cam_z < 0) cam_z = 0;
        if (cam_z > (256 << 8)) cam_z = 256 << 8;

        // Reset to start position
        if (key_hit(KEY_START))
        {
#ifdef AFFINITY_HAS_SPRITES
            cam_x     = AFN_CAM_X;
            cam_z     = AFN_CAM_Z;
            cam_h     = AFN_CAM_H;
            cam_angle = AFN_CAM_ANGLE;
            m7_horizon = AFN_CAM_HORIZON;
#else
            cam_x     = 128 << 8;
            cam_z     = 128 << 8;
            cam_h     = 64 << 8;
            cam_angle = 0;
            m7_horizon = 54;
#endif
        }

        // Project and draw sprites
        update_sprites();

        // Update minimap camera/sprite dots
        update_minimap();
    }

    return 0;
}
