// Affinity GBA Runtime — Mode 7 floor with orbit camera + OAM sprites
// Built with devkitARM + libtonc

#include <tonc.h>
#include <string.h>

// ---------------------------------------------------------------------------
// Map data — generated by editor, or fallback checkerboard
// ---------------------------------------------------------------------------

#include "mapdata.h"

// ---------------------------------------------------------------------------
// Mode 7 state
// ---------------------------------------------------------------------------

// Camera (16.8 fixed-point for position, angle in brads)
static FIXED cam_x;
static FIXED cam_z;
static FIXED cam_h;        // height above floor
static u16   cam_angle;    // brad angle
static FIXED cam_fov;      // focal distance D

// Precomputed sin/cos for current angle
static FIXED g_cosf, g_sinf;

// Horizon scanline — variable for pitch control (A/B buttons)
static int m7_horizon = 60;

// ---------------------------------------------------------------------------
// Orbit camera state (used when player sprite exists)
// ---------------------------------------------------------------------------

static FIXED player_x, player_z;   // player world position (16.8)
static FIXED player_y;             // player height (16.8)
static u16   orbit_angle;          // brad angle of camera around player
static FIXED orbit_dist;           // distance from player (16.8)
static int   player_sprite_idx = -1;
static int   player_moving;        // nonzero if D-pad held
static u16   player_move_angle;    // brad angle of last movement direction
static int   auto_orbit_smooth;   // smoothed auto-orbit value (fixed-point)

// Direction animation set tracking (for DMA streaming)
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
static int   g_active_dir_set[AFN_ASSET_COUNT]; // currently loaded direction set per asset
static int   g_anim_frame_counter; // VBlank counter for animation frame cycling
static int   g_current_anim[AFN_ASSET_COUNT];  // per-asset: 0=idle, 1=run, 2=sprint
static u8    g_asset_anim_enabled[AFN_ASSET_COUNT]; // per-asset: any sprite wants animation?
#endif

// ---------------------------------------------------------------------------
// Floor sprites — positions in 16.8 fixed-point
// ---------------------------------------------------------------------------

#define MAX_FLOOR_SPRITES 16

typedef struct {
    FIXED x;
    FIXED y;         // height above floor (16.8)
    FIXED z;
    u16   palIdx;    // OBJ palette color index
    s16   assetIdx;  // sprite asset index (-1 = default solid tile)
    FIXED scale;     // 8.8 fixed-point scale (256 = 1x)
    u16   rotation;  // world-space facing angle (brad, 0-65535)
    u8    animEnabled; // 0 = static, 1 = animate
    u8    spriteType;  // 0=Prop, 1=Player, 2=Enemy, etc.
    s16   meshIdx;     // index into mesh data (-1 = no mesh, use OAM sprite)
} FloorSpriteGBA;

static FloorSpriteGBA g_sprites[MAX_FLOOR_SPRITES];
static int g_spriteCount = 0;

#if defined(AFN_MESH_COUNT) && AFN_MESH_COUNT > 0
static int g_page = 0;
#endif

// Sprite projection result for sorting
typedef struct {
    int screenX;
    int screenY;
    int scale;    // 8.8 fixed-point scale (256 = 1x)
    int depth;    // for sorting (larger = farther)
    int idx;      // sprite index
} SpriteProjGBA;

// ---------------------------------------------------------------------------
// Mode 7 HBlank interrupt — per-scanline affine update
// ---------------------------------------------------------------------------

static void m7_hbl(void)
{
    int vc = REG_VCOUNT;

    // Above horizon: disable BG2 so backdrop color (sky) shows
    if (vc < m7_horizon)
    {
        REG_DISPCNT &= ~DCNT_BG2;
        return;
    }
    if (vc >= SCREEN_HEIGHT)
        return;

    // Re-enable BG2 at horizon
    REG_DISPCNT |= DCNT_BG2;

    // lambda = cam_height / (scanline - horizon)
    FIXED lam = cam_h * lu_div(vc - m7_horizon) >> 12;

    FIXED lcf = lam * g_cosf >> 8;
    FIXED lsf = lam * g_sinf >> 8;

    // Affine matrix — only PA and PC matter for per-scanline Mode 7
    REG_BG2PA =  lcf >> 4;
    REG_BG2PB = 0;
    REG_BG2PC =  lsf >> 4;
    REG_BG2PD = 0;

    // Reference point
    FIXED lxr, lyr;

    lxr = 120 * (lcf >> 4);
    lyr = cam_fov * (lsf >> 4);
    REG_BG2X = cam_x - lxr + lyr;

    lxr = 120 * (lsf >> 4);
    lyr = cam_fov * (lcf >> 4);
    REG_BG2Y = cam_z - lxr - lyr;
}

// ---------------------------------------------------------------------------
// Build checkerboard tiles + tilemap
// ---------------------------------------------------------------------------

static void load_checkerboard(void)
{
    pal_bg_mem[0] = RGB15(10, 16, 24);  // backdrop = sky blue
    pal_bg_mem[1] = RGB15(4, 10, 4);
    pal_bg_mem[2] = RGB15(8, 18, 8);
    pal_bg_mem[3] = RGB15(2, 6, 2);    // void/out-of-bounds dark green

    // Tile 0 = transparent (palette 0 = backdrop/sky blue) for out-of-bounds
    memset(&tile8_mem[2][0], 0, 64);

    // Tile 1 = solid dark, Tile 2 = solid light (full 8x8 each)
    memset(&tile8_mem[2][1], 1, 64);
    memset(&tile8_mem[2][2], 2, 64);

    // Fill 64x64 map: 2x2 tile checkerboard (each checker = 2x2 tiles = 16x16 px)
    {
        u8 *map = (u8*)se_mem[28];
        int y, x;
        memset(map, 0, 64 * 64);
        for (y = 0; y < 32; y++)
            for (x = 0; x < 32; x++)
                map[y * 64 + x] = (((x / 2) + (y / 2)) & 1) ? 2 : 1;
    }
}

#ifdef AFFINITY_HAS_MAPDATA
static void load_editor_map(void)
{
    memcpy(&tile8_mem[2][0], afn_tiles, afn_tilesLen);
    memcpy(pal_bg_mem, afn_palette, afn_paletteLen);
    // Tile the 32x32 map into 64x64 (2x2 repeat) to match editor floor density
    u8 *map = (u8*)se_mem[28];
    const u8 *src = (const u8*)afn_tilemap;
    int y, x;
    for (y = 0; y < 64; y++)
        for (x = 0; x < 64; x++)
            map[y * 64 + x] = src[(y & 31) * 32 + (x & 31)];
}
#endif

// ---------------------------------------------------------------------------
// OBJ sprite setup
// ---------------------------------------------------------------------------

static void init_obj_sprites(void)
{
    int i;
    REG_DISPCNT |= DCNT_OBJ | DCNT_OBJ_1D;

#ifdef AFN_ASSET_COUNT
#if AFN_ASSET_COUNT > 0
    // Copy all asset tile data into OBJ VRAM (charblock 4)
    {
        const u32 *src = afn_all_tiles;
        u32 *dst = (u32*)tile_mem[4];
        for (i = 0; i < (int)(AFN_ALL_TILES_LEN / 4); i++)
            dst[i] = src[i];
    }

    // Load per-asset palettes into OBJ palette banks
    for (i = 0; i < AFN_ASSET_COUNT; i++)
    {
        int palBank = afn_asset_desc[i][4];
        const u16 *pal = 0;
        switch (i) {
            case 0: pal = afn_pal0; break;
#if AFN_ASSET_COUNT > 1
            case 1: pal = afn_pal1; break;
#endif
#if AFN_ASSET_COUNT > 2
            case 2: pal = afn_pal2; break;
#endif
#if AFN_ASSET_COUNT > 3
            case 3: pal = afn_pal3; break;
#endif
#if AFN_ASSET_COUNT > 4
            case 4: pal = afn_pal4; break;
#endif
#if AFN_ASSET_COUNT > 5
            case 5: pal = afn_pal5; break;
#endif
#if AFN_ASSET_COUNT > 6
            case 6: pal = afn_pal6; break;
#endif
#if AFN_ASSET_COUNT > 7
            case 7: pal = afn_pal7; break;
#endif
            default: break;
        }
        if (pal)
        {
            int c;
            for (c = 0; c < 16; c++)
                pal_obj_mem[palBank * 16 + c] = pal[c];
        }
    }

    // Init direction animation set tracking — DMA set 0 from ROM at boot
#if defined(AFN_HAS_ASSET_DIRS) && AFN_ASSET_COUNT > 0
    {
        int ai;
        for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
        {
            g_active_dir_set[ai] = -1; // mark as unloaded so switch_dir_anim_set works
            g_current_anim[ai] = 0;
            g_asset_anim_enabled[ai] = 0;
        }
        g_anim_frame_counter = 0;
    }
#endif

    // Load per-asset direction palettes if present
#ifdef AFN_HAS_ASSET_DIRS
    {
        int ai;
        for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
        {
            if (!afn_asset_dir_desc[ai][4]) continue; // no directions
            int adPalBank = afn_asset_dir_desc[ai][3];
            const u16 *adPal = 0;
            switch (ai) {
                case 0: adPal = afn_pal_assetdir0; break;
#if AFN_ASSET_COUNT > 1
                case 1: adPal = afn_pal_assetdir1; break;
#endif
#if AFN_ASSET_COUNT > 2
                case 2: adPal = afn_pal_assetdir2; break;
#endif
#if AFN_ASSET_COUNT > 3
                case 3: adPal = afn_pal_assetdir3; break;
#endif
                default: break;
            }
            if (adPal)
            {
                int c;
                for (c = 0; c < 16; c++)
                    pal_obj_mem[adPalBank * 16 + c] = adPal[c];
            }
        }
    }
#endif

#endif
#else
    // No assets — use fallback solid 8x8 tile
    {
        u32 *t0 = (u32*)&tile_mem[4][0];
        int k;
        for (k = 0; k < 8; k++) t0[k] = 0x11111111;
    }
    pal_obj_mem[1*16 + 1] = RGB15(31, 31, 0);
    pal_obj_mem[2*16 + 1] = RGB15(31, 8, 8);
    pal_obj_mem[3*16 + 1] = RGB15(8, 8, 31);
    pal_obj_mem[4*16 + 1] = RGB15(8, 31, 8);
    pal_obj_mem[5*16 + 1] = RGB15(31, 16, 31);
#endif

    // Minimap dot tile
    {
#ifdef AFN_MINIMAP_TILE
        u32 *dot = (u32*)&tile_mem[4][AFN_MINIMAP_TILE];
#else
        u32 *dot = (u32*)&tile_mem[4][16];
#endif
        int k;
        for (k = 0; k < 8; k++) dot[k] = 0;
        dot[0] = 0x00000011;
        dot[1] = 0x00000011;
    }

    // Minimap palette bank (bank 6)
    pal_obj_mem[6*16 + 0] = 0;
    pal_obj_mem[6*16 + 1] = RGB15(31, 31, 31);
    pal_obj_mem[6*16 + 2] = RGB15(20, 20, 20);
    pal_obj_mem[6*16 + 3] = RGB15(31, 0, 0);

    oam_init(obj_mem, 128);
}

// Place demo sprites if no editor data
static void init_demo_sprites(void)
{
    g_sprites[0].x = 160 << 8;
    g_sprites[0].y = 0;
    g_sprites[0].z = 128 << 8;
    g_sprites[0].palIdx = 1;
    g_sprites[0].assetIdx = -1;
    g_sprites[0].scale = 256;
    g_sprites[0].meshIdx = -1;

    g_sprites[1].x = 96 << 8;
    g_sprites[1].y = 10 << 8;
    g_sprites[1].z = 96 << 8;
    g_sprites[1].palIdx = 2;
    g_sprites[1].assetIdx = -1;
    g_sprites[1].scale = 256;
    g_sprites[1].meshIdx = -1;

    g_sprites[2].x = 160 << 8;
    g_sprites[2].y = 0;
    g_sprites[2].z = 64 << 8;
    g_sprites[2].palIdx = 3;
    g_sprites[2].assetIdx = -1;
    g_sprites[2].scale = 256;
    g_sprites[2].meshIdx = -1;

    g_sprites[3].x = 64 << 8;
    g_sprites[3].y = 20 << 8;
    g_sprites[3].z = 160 << 8;
    g_sprites[3].palIdx = 4;
    g_sprites[3].assetIdx = -1;
    g_sprites[3].scale = 256;
    g_sprites[3].meshIdx = -1;

    g_spriteCount = 4;
}

#ifdef AFFINITY_HAS_SPRITES
#if AFN_SPRITE_COUNT > 0
static void load_editor_sprites(void)
{
    int i;
    int count = AFN_SPRITE_COUNT;
    if (count > MAX_FLOOR_SPRITES) count = MAX_FLOOR_SPRITES;

    for (i = 0; i < count; i++)
    {
        g_sprites[i].x           = afn_sprite_data[i][0];
        g_sprites[i].y           = afn_sprite_data[i][1];
        g_sprites[i].z           = afn_sprite_data[i][2];
        g_sprites[i].palIdx      = afn_sprite_data[i][3];
        g_sprites[i].assetIdx    = afn_sprite_data[i][4];
        g_sprites[i].scale       = afn_sprite_data[i][5];
        g_sprites[i].rotation    = (u16)afn_sprite_data[i][7];
        g_sprites[i].animEnabled = (u8)afn_sprite_data[i][8];
        g_sprites[i].spriteType  = (u8)afn_sprite_data[i][6];
#if defined(AFN_MESH_COUNT) && AFN_MESH_COUNT > 0
        g_sprites[i].meshIdx     = (s16)afn_sprite_data[i][9];
#else
        g_sprites[i].meshIdx     = -1;
#endif
    }
    g_spriteCount = count;
}
#endif
#endif

// ---------------------------------------------------------------------------
// DMA direction animation set switching
// ---------------------------------------------------------------------------

#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
static void switch_dir_anim_set(int assetIdx, int newSet)
{
    if (assetIdx < 0 || assetIdx >= AFN_ASSET_COUNT) return;
    if (!afn_asset_dir_desc[assetIdx][4]) return; // no directions
    int setCount = afn_asset_dir_desc[assetIdx][0];
    if (newSet < 0 || newSet >= setCount) return;
    if (g_active_dir_set[assetIdx] == newSet) return; // already loaded

    int tpf = afn_asset_dir_desc[assetIdx][1];       // tiles per direction frame
    int vramTile0 = afn_asset_dir_desc[assetIdx][5];  // VRAM destination tile index
    int romOffset = afn_dir_set_offsets[assetIdx][newSet]; // u32 index into ROM array
    if (romOffset < 0) return;

    // Copy 8 directions * tpf tiles * 32 bytes/tile from ROM to VRAM
    int wordCount = 8 * tpf * 8; // 8 dirs * tpf tiles * 8 u32s per tile
    const u32 *src = &afn_dir_anim_tiles[romOffset];
    u32 *dst = (u32*)&tile_mem[4][vramTile0];

    // Use DMA3 for fast ROM→VRAM copy (runs at ~2 cycles per word)
    DMA_TRANSFER(dst, src, wordCount, 3, DMA_NOW | DMA_32);

    g_active_dir_set[assetIdx] = newSet;
}
#endif

// Map baseSize to GBA OBJ ATTR1_SIZE bits
static u16 size_to_attr1(int baseSize)
{
    switch (baseSize) {
        case 8:  return ATTR1_SIZE_8;
        case 16: return ATTR1_SIZE_16;
        case 64: return ATTR1_SIZE_64;
        default: return ATTR1_SIZE_32;
    }
}

// ---------------------------------------------------------------------------
// Project sprites to screen and update OAM
// ---------------------------------------------------------------------------

static void update_sprites(void)
{
    SpriteProjGBA proj[MAX_FLOOR_SPRITES];
    int projCount = 0;
    int i, j;
    SpriteProjGBA tmp;

    for (i = 0; i < g_spriteCount; i++)
    {
        FIXED dx, dz, fovLambda, side, heightDiff;
        int screenY, screenX, scale;

        // Skip mesh sprites (rendered into bitmap, not OAM)
        if (g_sprites[i].meshIdx >= 0) continue;

        dx = g_sprites[i].x - cam_x;
        dz = g_sprites[i].z - cam_z;

        fovLambda = (dx * g_sinf - dz * g_cosf) >> 8;
        side      = (dx * g_cosf + dz * g_sinf) >> 8;

        if (fovLambda <= 64) continue;

        heightDiff = cam_h - g_sprites[i].y;
        screenY = m7_horizon + (int)((heightDiff * cam_fov) / fovLambda);
        screenX = 120 + (int)((side * cam_fov) / fovLambda);

        scale = (int)((cam_h * cam_fov) / fovLambda);

        // Use generous culling bounds (64x64 AFF_DBL = 128x128 canvas)
        if (screenY < -128 || screenY > 288) continue;
        if (screenX < -128 || screenX > 368) continue;
        if (scale < 1) continue;

        proj[projCount].screenX = screenX;
        proj[projCount].screenY = screenY;
        proj[projCount].scale   = scale;
        proj[projCount].depth   = fovLambda;
        proj[projCount].idx     = i;
        projCount++;
    }

    // Sort front-to-back
    for (i = 0; i < projCount - 1; i++)
        for (j = i + 1; j < projCount; j++)
            if (proj[i].depth > proj[j].depth)
            {
                tmp = proj[i];
                proj[i] = proj[j];
                proj[j] = tmp;
            }

    // Render projected sprites as affine OBJs
    for (i = 0; i < projCount && i < 16; i++)
    {
        int oamIdx = 16 + i;
        int affIdx = i;
        int sprIdx = proj[i].idx;
        int palBank = g_sprites[sprIdx].palIdx;
        int tileId = 0;
        int baseSize = 32; // default for player dir sprites
        int scaleSize = 32; // size used for scale calculation (asset's original frame size)

        // Resolve tile/palette from asset (both player and non-player sprites)
        {
#ifdef AFN_ASSET_COUNT
#if AFN_ASSET_COUNT > 0
            {
                int ai = g_sprites[sprIdx].assetIdx;
                if (ai >= 0 && ai < AFN_ASSET_COUNT)
                {
                    scaleSize = afn_asset_desc[ai][3];
#ifdef AFN_HAS_ASSET_DIRS
                    // Check if this asset has directional sprites
                    if (afn_asset_dir_desc[ai][4])
                    {
                        int dirIdx;
                        if (sprIdx == player_sprite_idx)
                        {
                            // Player direction: based on movement/orbit angle (NOT camera-to-sprite)
                            u16 sprAngle;
                            if (player_moving)
                                sprAngle = player_move_angle;
                            else
                                sprAngle = orbit_angle + player_move_angle;
                            int rawIdx = ((sprAngle + 0xC000 + 4096) >> 13) & 7;
                            dirIdx = (8 - rawIdx) & 7;
                        }
                        else
                        {
                            // Non-player: compute angle from camera to sprite
                            FIXED dx = g_sprites[sprIdx].x - cam_x;
                            FIXED dz = g_sprites[sprIdx].z - cam_z;
                            u16 angleToSprite = ArcTan2(dx >> 4, -(dz >> 4));
                            u16 relAngle = angleToSprite + 0x4000 - g_sprites[sprIdx].rotation;
                            dirIdx = ((relAngle + 0x1000) >> 13) & 7;
                        }
                        {
                            int adTpf = afn_asset_dir_desc[ai][1];
                            int vramTile0 = afn_asset_dir_desc[ai][5];
                            tileId = vramTile0 + dirIdx * adTpf;
                            baseSize = afn_asset_dir_desc[ai][2];
                            scaleSize = baseSize; // use direction size for scaling
                            palBank = afn_asset_dir_desc[ai][3];
                        }
                    }
                    else
#endif
                    {
                        tileId = afn_asset_desc[ai][0];
                        baseSize = afn_asset_desc[ai][3];
                        palBank = afn_asset_desc[ai][4];
                    }
                }
            }
#endif
#endif
        }

        if (palBank > 15) palBank = 1;

        // Skip sprites with no valid asset (prevents rogue pixels)
        if (g_sprites[sprIdx].assetIdx < 0)
        {
            obj_mem[16 + i].attr0 = ATTR0_HIDE;
            continue;
        }

        {
            int sprScale = g_sprites[sprIdx].scale;
            int invScale;
            int canvasHalf = baseSize; // AFF_DBL canvas = 2 * baseSize
            if (sprScale <= 0) sprScale = 256;

            // Scale based on scaleSize (asset's original frame size) so direction
            // sprites (64x64) appear the same on-screen size as regular frames (32x32)
            invScale = (proj[i].depth * 14 * baseSize) / (sprScale * scaleSize);
            // invScale=128 means 2x magnification, which exactly fills the
            // AFF_DBL canvas (2*baseSize).  Going lower clips the sprite.
            if (invScale < 128) invScale = 128;
            if (invScale > 2048) invScale = 2048;

            obj_aff_mem[affIdx].pa = (s16)invScale;
            obj_aff_mem[affIdx].pb = 0;
            obj_aff_mem[affIdx].pc = 0;
            obj_aff_mem[affIdx].pd = (s16)invScale;

            int visHalf = (baseSize * 128) / invScale;
            int sx = proj[i].screenX - canvasHalf;
            int sy = proj[i].screenY - canvasHalf - visHalf;

            obj_mem[oamIdx].attr0 = ATTR0_Y(sy & 0xFF) | ATTR0_SQUARE | ATTR0_AFF_DBL;
            obj_mem[oamIdx].attr1 = ATTR1_X(sx & 0x1FF) | size_to_attr1(baseSize) | ATTR1_AFF_ID(affIdx);
            obj_mem[oamIdx].attr2 = ATTR2_ID(tileId) | ATTR2_PRIO(0) | ATTR2_PALBANK(palBank);
        }
    }

    // Hide remaining floor sprite OBJ slots
    for (; i < 16; i++)
    {
        obj_mem[16 + i].attr0 = ATTR0_HIDE;
    }
}

// ---------------------------------------------------------------------------
// Minimap
// ---------------------------------------------------------------------------

#define MINIMAP_X  4
#define MINIMAP_Y  124
#define MINIMAP_W  32
#define MINIMAP_H  32

#define TILE_MINIMAP_BG    1
#define TILE_MINIMAP_GRID  2
#define TILE_MINIMAP_CAM   3

static void init_minimap(void)
{
    REG_BG0CNT = BG_CBB(0) | BG_SBB(30) | BG_4BPP | BG_REG_32x32 | BG_PRIO(0);

    pal_bg_mem[16 + 0] = 0;
    pal_bg_mem[16 + 1] = RGB15(2, 4, 2);
    pal_bg_mem[16 + 2] = RGB15(5, 10, 5);
    pal_bg_mem[16 + 3] = RGB15(31, 31, 31);

    {
        u32 *t = (u32*)&tile_mem[0][TILE_MINIMAP_BG];
        int k;
        for (k = 0; k < 8; k++)
            t[k] = 0x11111111;
    }

    {
        u32 *t = (u32*)&tile_mem[0][TILE_MINIMAP_GRID];
        int k;
        t[0] = 0x22222222;
        for (k = 1; k < 7; k++)
            t[k] = 0x11111112;
        t[7] = 0x22222222;
    }

    {
        u16 *map = (u16*)se_mem[30];
        int k;
        for (k = 0; k < 32*32; k++)
            map[k] = 0;
    }

    {
        u16 *map = (u16*)se_mem[30];
        int tx, ty;
        for (ty = 0; ty < 4; ty++)
            for (tx = 0; tx < 4; tx++)
                map[ty * 32 + tx] = TILE_MINIMAP_GRID | SE_PALBANK(1);
    }

    REG_BG0HOFS = (512 - MINIMAP_X) & 0x1FF;
    REG_BG0VOFS = (512 - MINIMAP_Y) & 0x1FF;
}

static void update_minimap(void)
{
    int i;
    int oamIdx = 0;

    // Camera/player position dot
    FIXED dotX = (player_sprite_idx >= 0) ? player_x : cam_x;
    FIXED dotZ = (player_sprite_idx >= 0) ? player_z : cam_z;

    int camMX = MINIMAP_X + ((dotX >> 8) >> 3);
    int camMY = MINIMAP_Y + ((dotZ >> 8) >> 3);

    if (camMX < MINIMAP_X) camMX = MINIMAP_X;
    if (camMX > MINIMAP_X + MINIMAP_W - 1) camMX = MINIMAP_X + MINIMAP_W - 1;
    if (camMY < MINIMAP_Y) camMY = MINIMAP_Y;
    if (camMY > MINIMAP_Y + MINIMAP_H - 1) camMY = MINIMAP_Y + MINIMAP_H - 1;

    {
#ifdef AFN_MINIMAP_TILE
        int dotTile = AFN_MINIMAP_TILE;
#else
        int dotTile = 16;
#endif
        obj_mem[oamIdx].attr0 = ATTR0_Y(camMY & 0xFF) | ATTR0_SQUARE;
        obj_mem[oamIdx].attr1 = ATTR1_X(camMX & 0x1FF) | ATTR1_SIZE_8;
        obj_mem[oamIdx].attr2 = ATTR2_ID(dotTile) | ATTR2_PRIO(0) | ATTR2_PALBANK(6);
    }
    oamIdx++;

    for (i = 0; i < g_spriteCount && oamIdx < 16; i++)
    {
        if (i == player_sprite_idx) continue; // player already shown as main dot
        int smx = MINIMAP_X + ((g_sprites[i].x >> 8) >> 3);
        int smy = MINIMAP_Y + ((g_sprites[i].z >> 8) >> 3);

        if (smx < MINIMAP_X || smx > MINIMAP_X + MINIMAP_W - 1) continue;
        if (smy < MINIMAP_Y || smy > MINIMAP_Y + MINIMAP_H - 1) continue;

        int palBank = g_sprites[i].palIdx;
        if (palBank > 5) palBank = 1;

        {
#ifdef AFN_MINIMAP_TILE
            int dotTile = AFN_MINIMAP_TILE;
#else
            int dotTile = 16;
#endif
            obj_mem[oamIdx].attr0 = ATTR0_Y(smy & 0xFF) | ATTR0_SQUARE;
            obj_mem[oamIdx].attr1 = ATTR1_X(smx & 0x1FF) | ATTR1_SIZE_8;
            obj_mem[oamIdx].attr2 = ATTR2_ID(dotTile) | ATTR2_PRIO(0) | ATTR2_PALBANK(palBank);
        }
        oamIdx++;
    }

    for (; oamIdx < 16; oamIdx++)
    {
        obj_mem[oamIdx].attr0 = ATTR0_HIDE;
    }
}

// ---------------------------------------------------------------------------
// Software 3D mesh rendering (Mode 4 bitmap)
// ---------------------------------------------------------------------------

#if defined(AFN_MESH_COUNT) && AFN_MESH_COUNT > 0

// Write a single pixel to Mode 4 framebuffer (handles 16-bit VRAM access)
static inline void m4_plot_buf(u16* buf, int x, int y, u8 palIdx)
{
    int idx;
    if (x < 0 || x >= 240 || y < 0 || y >= 160) return;
    idx = y * 120 + (x >> 1);
    if (x & 1)
        buf[idx] = (buf[idx] & 0x00FF) | ((u16)palIdx << 8);
    else
        buf[idx] = (buf[idx] & 0xFF00) | palIdx;
}

// Software render Mode 7 floor into bitmap buffer
IWRAM_CODE static void render_floor_sw(u16* buf)
{
    int y, x;
    // Sky fill (palette index 0 = sky blue)
    u16 skyPair = 0; // both bytes = palette 0
    for (y = 0; y < m7_horizon && y < 160; y++)
    {
        u16* row = buf + y * 120;
        for (x = 0; x < 120; x++)
            row[x] = skyPair;
    }

    // Floor scanlines
    for (y = (m7_horizon < 0 ? 0 : m7_horizon); y < 160; y++)
    {
        FIXED lam, lcf, lsf, wx, wz;
        u16* row;
        int dy = y - m7_horizon;
        if (dy <= 0) continue;

        lam = (cam_h * lu_div(dy)) >> 12;
        lcf = (lam * g_cosf) >> 8;
        lsf = (lam * g_sinf) >> 8;

        wx = cam_x + (-120 * lcf) + (cam_fov * lsf);
        wz = cam_z + (-120 * lsf) - (cam_fov * lcf);

        row = buf + y * 120;
        for (x = 0; x < 120; x++)
        {
            int cx0, cx1;
            u8 p0, p1;
            // Sample two pixels
            cx0 = ((wx >> 13) ^ (wz >> 13)) & 1;
            p0 = cx0 ? 2 : 1;
            wx += lcf; wz += lsf;

            cx1 = ((wx >> 13) ^ (wz >> 13)) & 1;
            p1 = cx1 ? 2 : 1;
            wx += lcf; wz += lsf;

            row[x] = p0 | (p1 << 8);
        }
    }
}

// Fill a horizontal span in Mode 4 bitmap (handles odd-pixel edges + DMA bulk fill)
IWRAM_CODE static void afn_hline(u16* row, int left, int right, u8 palIdx)
{
    int lx = left, rx = right, count;
    u16 pair;
    /* Handle odd left pixel */
    if ((lx & 1) && lx <= rx)
    { row[lx >> 1] = (row[lx >> 1] & 0x00FF) | ((u16)palIdx << 8); lx++; }
    /* Handle even right pixel */
    if (!(rx & 1) && rx >= lx)
    { row[rx >> 1] = (row[rx >> 1] & 0xFF00) | palIdx; rx--; }
    /* Bulk fill aligned pairs */
    count = (rx - lx + 1) >> 1;
    if (count > 0)
    {
        pair = palIdx | ((u16)palIdx << 8);
        if (count >= 4)
            memset16(&row[lx >> 1], pair, count);
        else
            while (count--) { row[lx >> 1] = pair; lx += 2; }
    }
}

// Rasterize a flat-shaded triangle into Mode 4 bitmap
// Uses 16.16 fixed-point edge walking — no division in scanline loop
IWRAM_CODE static void rasterize_tri(u16* buf, int x0, int y0, int x1, int y1, int x2, int y2, u8 palIdx)
{
    int tmp;
    int totalH, segH;
    int iy0, iy2, y;
    int xLong, xShort;
    int dxLong, dxShort; /* 16.16 fixed-point x step per scanline */
    int left, right;

    /* Sort by y */
    if (y0 > y1) { tmp=x0; x0=x1; x1=tmp; tmp=y0; y0=y1; y1=tmp; }
    if (y0 > y2) { tmp=x0; x0=x2; x2=tmp; tmp=y0; y0=y2; y2=tmp; }
    if (y1 > y2) { tmp=x1; x1=x2; x2=tmp; tmp=y1; y1=y2; y2=tmp; }

    totalH = y2 - y0;
    if (totalH <= 0) return;

    /* Long edge slope (16.16 fixed) — one divide total */
    dxLong = ((x2 - x0) << 16) / totalH;

    /* Upper half: y0 -> y1 */
    segH = y1 - y0;
    if (segH > 0)
    {
        dxShort = ((x1 - x0) << 16) / segH;
        xLong = x0 << 16;
        xShort = x0 << 16;

        /* Skip rows above screen */
        iy0 = y0 < 0 ? 0 : y0;
        if (iy0 > y0)
        {
            xLong += dxLong * (iy0 - y0);
            xShort += dxShort * (iy0 - y0);
        }
        iy2 = y1 < 160 ? y1 : 160;

        for (y = iy0; y < iy2; y++)
        {
            left = xLong >> 16;
            right = xShort >> 16;
            if (left > right) { tmp = left; left = right; right = tmp; }
            if (left < 0) left = 0;
            if (right > 239) right = 239;
            if (left <= right)
                afn_hline(buf + y * 120, left, right, palIdx);
            xLong += dxLong;
            xShort += dxShort;
        }
    }

    /* Lower half: y1 -> y2 */
    segH = y2 - y1;
    if (segH > 0)
    {
        dxShort = ((x2 - x1) << 16) / segH;
        /* Long edge continues from where it was at y1 */
        xLong = (x0 << 16) + dxLong * (y1 - y0);
        xShort = x1 << 16;

        iy0 = y1 < 0 ? 0 : y1;
        if (iy0 > y1)
        {
            xLong += dxLong * (iy0 - y1);
            xShort += dxShort * (iy0 - y1);
        }
        iy2 = y2 < 160 ? y2 : 159;

        for (y = iy0; y <= iy2; y++)
        {
            left = xLong >> 16;
            right = xShort >> 16;
            if (left > right) { tmp = left; left = right; right = tmp; }
            if (left < 0) left = 0;
            if (right > 239) right = 239;
            if (left <= right)
                afn_hline(buf + y * 120, left, right, palIdx);
            xLong += dxLong;
            xShort += dxShort;
        }
    }
}

// Half-res rasterizer: draws every other scanline, duplicating each to the row below.
// Halves the number of afn_hline calls (the main fill bottleneck).
IWRAM_CODE static void rasterize_tri_half(u16* buf, int x0, int y0, int x1, int y1, int x2, int y2, u8 palIdx)
{
    int tmp;
    int totalH, segH;
    int iy0, iy2, y;
    int xLong, xShort;
    int dxLong, dxShort;
    int left, right;

    if (y0 > y1) { tmp=x0; x0=x1; x1=tmp; tmp=y0; y0=y1; y1=tmp; }
    if (y0 > y2) { tmp=x0; x0=x2; x2=tmp; tmp=y0; y0=y2; y2=tmp; }
    if (y1 > y2) { tmp=x1; x1=x2; x2=tmp; tmp=y1; y1=y2; y2=tmp; }

    totalH = y2 - y0;
    if (totalH <= 0) return;

    dxLong = ((x2 - x0) << 16) / totalH;

    segH = y1 - y0;
    if (segH > 0)
    {
        dxShort = ((x1 - x0) << 16) / segH;
        xLong = x0 << 16;
        xShort = x0 << 16;

        iy0 = y0 < 0 ? 0 : y0;
        if (iy0 > y0)
        {
            xLong += dxLong * (iy0 - y0);
            xShort += dxShort * (iy0 - y0);
        }
        /* Align to even scanline */
        if (iy0 & 1) { xLong += dxLong; xShort += dxShort; iy0++; }
        iy2 = y1 < 160 ? y1 : 160;

        for (y = iy0; y < iy2; y += 2)
        {
            left = xLong >> 16;
            right = xShort >> 16;
            if (left > right) { tmp = left; left = right; right = tmp; }
            if (left < 0) left = 0;
            if (right > 239) right = 239;
            if (left <= right)
            {
                afn_hline(buf + y * 120, left, right, palIdx);
                if (y + 1 < 160)
                    afn_hline(buf + (y + 1) * 120, left, right, palIdx);
            }
            xLong += dxLong << 1;
            xShort += dxShort << 1;
        }
    }

    segH = y2 - y1;
    if (segH > 0)
    {
        dxShort = ((x2 - x1) << 16) / segH;
        xLong = (x0 << 16) + dxLong * (y1 - y0);
        xShort = x1 << 16;

        iy0 = y1 < 0 ? 0 : y1;
        if (iy0 > y1)
        {
            xLong += dxLong * (iy0 - y1);
            xShort += dxShort * (iy0 - y1);
        }
        if (iy0 & 1) { xLong += dxLong; xShort += dxShort; iy0++; }
        iy2 = y2 < 160 ? y2 : 159;

        for (y = iy0; y <= iy2; y += 2)
        {
            left = xLong >> 16;
            right = xShort >> 16;
            if (left > right) { tmp = left; left = right; right = tmp; }
            if (left < 0) left = 0;
            if (right > 239) right = 239;
            if (left <= right)
            {
                afn_hline(buf + y * 120, left, right, palIdx);
                if (y + 1 < 160)
                    afn_hline(buf + (y + 1) * 120, left, right, palIdx);
            }
            xLong += dxLong << 1;
            xShort += dxShort << 1;
        }
    }
}

// Triangle sort entry for painter's algorithm
typedef struct { int triIdx; int depth; } TriSort;

// Render all mesh sprites into the bitmap
IWRAM_CODE static void render_meshes_sw(u16* buf)
{
    int i;
    for (i = 0; i < g_spriteCount; i++)
    {
        int mi, vertCount, idxCount, cullMode, meshLit, meshSorted, meshHalfRes, v, t;
        int anyVisible;
        const s16* verts;
        const s8* norms;
        const u16* indices;
        FIXED cosR, sinR, sprScale;
        int sx[512], sy[512];
        FIXED sz[512]; // depth per vertex for sorting
        u8 vis[512];
        TriSort triOrder[256];
        int triCount;

        if (g_sprites[i].meshIdx < 0 || g_sprites[i].meshIdx >= AFN_MESH_COUNT)
            continue;

        mi = g_sprites[i].meshIdx;
        verts = afn_mesh_vert_ptrs[mi];
        norms = afn_mesh_norm_ptrs[mi];
        indices = afn_mesh_idx_ptrs[mi];
        vertCount = afn_mesh_desc[mi][0];
        idxCount = afn_mesh_desc[mi][1];
        cullMode = afn_mesh_desc[mi][3]; // 0=Back, 1=Front, 2=None
        meshLit = afn_mesh_desc[mi][4];  // 0=unlit, 1=lit
        meshSorted = afn_mesh_desc[mi][5]; // 0=unsorted, 1=pre-sorted (skip depth sort)
        meshHalfRes = afn_mesh_desc[mi][6]; // 0=full, 1=skip every other scanline

        // Sprite transform
        cosR = lu_cos(g_sprites[i].rotation) >> 4;
        sinR = lu_sin(g_sprites[i].rotation) >> 4;
        sprScale = g_sprites[i].scale;
        if (sprScale <= 0) sprScale = 256;

        if (vertCount > 512) vertCount = 512;

        for (v = 0; v < vertCount; v++)
        {
            // Local vertex (8.8 fixed)
            FIXED vx = verts[v * 3 + 0];
            FIXED vy = verts[v * 3 + 1];
            FIXED vz = verts[v * 3 + 2];
            FIXED rx, ry, rz, wx, wy, wz, dx, dz, fovLambda, heightDiff, side;

            // Scale (8.8 * 8.8 >> 8 = 8.8)
            vx = (vx * sprScale) >> 8;
            vy = (vy * sprScale) >> 8;
            vz = (vz * sprScale) >> 8;

            // Rotate around Y axis
            rx = (vx * cosR + vz * sinR) >> 8;
            ry = vy;
            rz = (-vx * sinR + vz * cosR) >> 8;

            // World position
            wx = g_sprites[i].x + rx;
            wy = g_sprites[i].y + ry;
            wz = g_sprites[i].z + rz;

            // Mode 7 projection
            dx = wx - cam_x;
            dz = wz - cam_z;
            fovLambda = (dx * g_sinf - dz * g_cosf) >> 8;

            if (fovLambda <= 64) { vis[v] = 0; continue; }

            sz[v] = fovLambda; // store depth for painter's sort

            heightDiff = cam_h - wy;
            sy[v] = m7_horizon + (int)((heightDiff * cam_fov) / fovLambda);
            side = (dx * g_cosf + dz * g_sinf) >> 8;
            sx[v] = 120 + (int)((side * cam_fov) / fovLambda);
            vis[v] = 1;
        }

        // Whole-mesh screen cull: skip if no vertices are visible
        anyVisible = 0;
        for (v = 0; v < vertCount; v++)
            if (vis[v]) { anyVisible = 1; break; }
        if (!anyVisible) continue;

        // Build triangle list with backface culling
        triCount = 0;
        for (t = 0; t < idxCount / 3; t++)
        {
            int i0 = indices[t * 3 + 0];
            int i1 = indices[t * 3 + 1];
            int i2 = indices[t * 3 + 2];
            int cross;

            if (i0 >= vertCount || i1 >= vertCount || i2 >= vertCount) continue;
            if (i0 == i1 || i1 == i2 || i0 == i2) continue; // degenerate
            if (!vis[i0] || !vis[i1] || !vis[i2]) continue;

            // Screen bounds cull: skip if all 3 vertices fully offscreen
            if ((sx[i0] < 0 && sx[i1] < 0 && sx[i2] < 0) ||
                (sx[i0] >= 240 && sx[i1] >= 240 && sx[i2] >= 240) ||
                (sy[i0] < 0 && sy[i1] < 0 && sy[i2] < 0) ||
                (sy[i0] >= 160 && sy[i1] >= 160 && sy[i2] >= 160))
                continue;

            // Backface culling: screen-space cross product
            cross = (sx[i1] - sx[i0]) * (sy[i2] - sy[i0])
                  - (sy[i1] - sy[i0]) * (sx[i2] - sx[i0]);
            if (cullMode == 0 && cross >= 0) continue;      // Back: cull back faces
            else if (cullMode == 1 && cross <= 0) continue;  // Front: cull front faces
            // cullMode == 2 (None): no culling, draw all

#ifdef AFN_SMALL_TRI_CULL
            // Small triangle cull: skip if screen-space area too small
            {
                int area = cross < 0 ? -cross : cross;
                if (area < AFN_SMALL_TRI_CULL) continue;
            }
#endif

            // Average depth for painter's sort (larger = farther)
            {
                int avgDepth = sz[i0] + sz[i1] + sz[i2];
#ifdef AFN_DRAW_DISTANCE
                // Per-triangle draw distance cull (depth is sum of 3 vertices in 16.8)
                if (avgDepth / 3 > AFN_DRAW_DISTANCE) continue;
#endif
                triOrder[triCount].triIdx = t;
                triOrder[triCount].depth = avgDepth;
                triCount++;
                if (triCount >= 256) break;
            }
        }

        // Insertion sort by depth — back to front (farthest first)
        // Pre-sorted meshes (Barebones) skip this entirely
        if (!meshSorted)
        {
            int a, b;
            for (a = 1; a < triCount; a++)
            {
                TriSort tmp = triOrder[a];
                b = a - 1;
                while (b >= 0 && triOrder[b].depth < tmp.depth)
                {
                    triOrder[b + 1] = triOrder[b];
                    b--;
                }
                triOrder[b + 1] = tmp;
            }
        }

        // Draw sorted triangles with flat shading
        for (t = 0; t < triCount; t++)
        {
            int ti = triOrder[t].triIdx;
            int i0 = indices[ti * 3 + 0];
            int i1 = indices[ti * 3 + 1];
            int i2 = indices[ti * 3 + 2];
            int nx, ny, nz, rnx, rny, rnz, dot, shade;
            u8 palIdx;

            if (meshLit)
            {
                // Face normal (average vertex normals, 0.7 fixed)
                nx = ((int)norms[i0*3+0] + norms[i1*3+0] + norms[i2*3+0]) / 3;
                ny = ((int)norms[i0*3+1] + norms[i1*3+1] + norms[i2*3+1]) / 3;
                nz = ((int)norms[i0*3+2] + norms[i1*3+2] + norms[i2*3+2]) / 3;

                // Rotate normal by sprite rotation
                rnx = (nx * (cosR >> 4) + nz * (sinR >> 4)) >> 4;
                rny = ny;
                rnz = (-nx * (sinR >> 4) + nz * (cosR >> 4)) >> 4;

                // Dot with light direction (0.3, -0.8, 0.5) as fixed ~ (38, -102, 64) in 0.7
                dot = -(rnx * 38 + rny * (-102) + rnz * 64) >> 7;
                shade = (dot >> 4) + 3;
                if (shade < 0) shade = 0;
                if (shade > 7) shade = 7;

                palIdx = AFN_MESH_PAL_BASE + mi * 8 + shade;
            }
            else
            {
                // Unlit: use middle shade (flat color, no lighting calc)
                palIdx = AFN_MESH_PAL_BASE + mi * 8 + 5;
            }

            if (meshHalfRes)
                rasterize_tri_half(buf, sx[i0], sy[i0], sx[i1], sy[i1], sx[i2], sy[i2], palIdx);
            else
                rasterize_tri(buf, sx[i0], sy[i0], sx[i1], sy[i1], sx[i2], sy[i2], palIdx);
        }
    }
}

// Draw minimap background into bitmap (since BG0 not available in Mode 4)
static void render_minimap_bg_sw(u16* buf)
{
    int ty, tx;
    // Draw 32x32 minimap background at (4, 124)
    for (ty = 0; ty < 32; ty++)
    {
        int py = 124 + ty;
        if (py >= 160) break;
        for (tx = 0; tx < 32; tx++)
        {
            int px = 4 + tx;
            // Grid lines every 8 pixels
            u8 col = ((tx & 7) == 0 || (ty & 7) == 0) ? 4 : 3;
            m4_plot_buf(buf, px, py, col);
        }
    }
}

#endif /* AFN_MESH_COUNT > 0 */

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

int main(void)
{
    // --- Video setup ---
#if defined(AFN_MESH_COUNT) && AFN_MESH_COUNT > 0
    REG_DISPCNT = DCNT_MODE4 | DCNT_BG2 | DCNT_OBJ | DCNT_OBJ_1D;
    // Set up BG palette for bitmap rendering
    pal_bg_mem[0] = RGB15(10, 16, 24);  // sky
    pal_bg_mem[1] = RGB15(4, 10, 4);    // checker dark
    pal_bg_mem[2] = RGB15(8, 18, 8);    // checker light
    pal_bg_mem[3] = RGB15(2, 4, 2);     // minimap bg
    pal_bg_mem[4] = RGB15(5, 10, 5);    // minimap grid
    // Load mesh shading palette
    {
        int k;
        for (k = 0; k < AFN_MESH_COUNT * 8; k++)
            pal_bg_mem[AFN_MESH_PAL_BASE + k] = afn_mesh_palette[k];
    }
#else
    REG_DISPCNT = DCNT_MODE1 | DCNT_BG0 | DCNT_BG2;
#endif

#if !defined(AFN_MESH_COUNT) || AFN_MESH_COUNT == 0
    REG_BG2CNT = BG_CBB(2) | BG_SBB(28) | BG_AFF_64x64 | BG_8BPP | BG_PRIO(2);

    REG_BG2PA = 0x0100;
    REG_BG2PB = 0;
    REG_BG2PC = 0;
    REG_BG2PD = 0x0100;
    REG_BG2X  = 0;
    REG_BG2Y  = 0;

    // --- Load map data ---
#ifdef AFFINITY_HAS_MAPDATA
    load_editor_map();
#else
    load_checkerboard();
#endif
#endif /* !AFN_MESH_COUNT */

    // --- OBJ sprite setup ---
    init_obj_sprites();

    // DMA direction animation set 0 from ROM to VRAM at boot
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
    {
        int ai;
        for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
        {
            if (!afn_asset_dir_desc[ai][4]) continue;
            switch_dir_anim_set(ai, 0);
        }
    }
#endif

    // --- Minimap setup ---
#if !defined(AFN_MESH_COUNT) || AFN_MESH_COUNT == 0
    init_minimap();
#endif

#if defined(AFFINITY_HAS_SPRITES) && AFN_SPRITE_COUNT > 0
    load_editor_sprites();
#else
    #ifndef AFFINITY_HAS_MAPDATA
    init_demo_sprites();
    #endif
#endif

    // Determine which assets have animation-enabled sprites (must be after load_editor_sprites)
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
#if defined(AFN_SPRITE_COUNT) && AFN_SPRITE_COUNT > 0
    {
        int si;
        for (si = 0; si < g_spriteCount; si++)
        {
            int aidx = g_sprites[si].assetIdx;
            if (aidx >= 0 && aidx < AFN_ASSET_COUNT && g_sprites[si].animEnabled
                && g_sprites[si].spriteType == 1) // 1 = Player
                g_asset_anim_enabled[aidx] = 1;
        }
    }
#endif
#endif

    // --- Camera init ---
#ifdef AFFINITY_HAS_SPRITES
    cam_x     = AFN_CAM_X;
    cam_z     = AFN_CAM_Z;
    cam_h     = AFN_CAM_H;
    cam_angle = AFN_CAM_ANGLE;
    cam_fov   = 128;
    m7_horizon = AFN_CAM_HORIZON;
#else
    cam_x     = 128 << 8;
    cam_z     = 128 << 8;
    cam_h     = 14 << 8;
    cam_angle = 0;
    cam_fov   = 128;
#endif

    // --- Orbit camera init ---
    player_sprite_idx = -1;
#if defined(AFN_PLAYER_IDX) && AFN_PLAYER_IDX >= 0
    player_sprite_idx = AFN_PLAYER_IDX;
    player_x = g_sprites[AFN_PLAYER_IDX].x;
    player_z = g_sprites[AFN_PLAYER_IDX].z;
    player_y = g_sprites[AFN_PLAYER_IDX].y;
    orbit_angle = AFN_CAM_ANGLE;
    orbit_dist = AFN_ORBIT_DIST;
    player_moving = 0;
    player_move_angle = 0x4000; // face away from camera (show back)
#endif

    // Precompute initial sin/cos
    g_cosf = lu_cos(cam_angle) >> 4;
    g_sinf = lu_sin(cam_angle) >> 4;

    // --- Set up HBlank interrupt ---
    irq_init(NULL);
    irq_add(II_VBLANK, NULL);
#if !defined(AFN_MESH_COUNT) || AFN_MESH_COUNT == 0
    irq_add(II_HBLANK, m7_hbl);
#endif

    // --- Main loop ---
    while (1)
    {
#if defined(AFN_MESH_COUNT) && AFN_MESH_COUNT > 0
        // Software render to back buffer
        {
            u16* backbuf = g_page ? (u16*)0x06000000 : (u16*)0x0600A000;
            // DMA fill with sky color (palette 0) — fast clear
            {
                u32 fill = 0;
                DMA_TRANSFER(backbuf, &fill, 120 * 160 / 2, 3, DMA_NOW | DMA_32 | DMA_SRC_FIXED);
            }
            render_meshes_sw(backbuf);
        }
#endif
        VBlankIntrWait();
#if defined(AFN_MESH_COUNT) && AFN_MESH_COUNT > 0
        // Flip page
        g_page ^= 1;
        REG_DISPCNT = DCNT_MODE4 | DCNT_BG2 | DCNT_OBJ | DCNT_OBJ_1D | (g_page ? DCNT_PAGE : 0);
#else
        REG_DISPCNT &= ~DCNT_BG2;
#endif
        key_poll();

        if (player_sprite_idx >= 0)
        {
            // ============================================================
            // ORBIT CAMERA MODE — Asterix XXL style
            // ============================================================

#ifdef AFN_WALK_SPEED
            FIXED moveSpeed = key_is_down(KEY_B) ? AFN_SPRINT_SPEED : AFN_WALK_SPEED;
#else
            FIXED moveSpeed = key_is_down(KEY_B) ? 56 : 37;
#endif
            int   rotSpeed  = 0x0200;

            // View angle = orbit_angle (camera is behind player, looking forward)
            u16 viewAngle = orbit_angle;
            FIXED viewSin = lu_sin(viewAngle) >> 4;
            FIXED viewCos = lu_cos(viewAngle) >> 4;

            // D-pad = player movement
            FIXED inputFwd = 0, inputRight = 0;
            if (key_is_down(KEY_UP))    inputFwd   += 256;
            if (key_is_down(KEY_DOWN))  inputFwd   -= 256;
            if (key_is_down(KEY_LEFT))  inputRight -= 256;
            if (key_is_down(KEY_RIGHT)) inputRight += 256;

            // Normalize diagonal (~0.707)
            if (inputFwd && inputRight)
            {
                inputFwd   = (inputFwd * 181) >> 8;
                inputRight = (inputRight * 181) >> 8;
            }

            int wasMoving = player_moving;

            // L/R shoulder = manual orbit (always applies)
            if (key_is_down(KEY_L))
                orbit_angle -= rotSpeed;
            if (key_is_down(KEY_R))
                orbit_angle += rotSpeed;

            // Auto-orbit when strafing (LEFT/RIGHT) with drag on release
            {
                int autoOrbitTarget = 0;
                if (inputRight)
                {
                    autoOrbitTarget = (rotSpeed * 2 / 5);  // 40% of rotSpeed
                    if (inputRight < 0)
                        autoOrbitTarget = -autoOrbitTarget;
                    if (key_is_down(KEY_L) || key_is_down(KEY_R))
                        autoOrbitTarget *= 2;
                }
                if (autoOrbitTarget != 0)
                    auto_orbit_smooth += (autoOrbitTarget - auto_orbit_smooth) >> 2;
                else
                {
                    // Decay toward zero (handle negative values correctly)
                    if (auto_orbit_smooth > 0)
                        auto_orbit_smooth = (auto_orbit_smooth * 7) >> 3;  // ~0.875 decay
                    else if (auto_orbit_smooth < 0)
                        auto_orbit_smooth = -(((-auto_orbit_smooth) * 7) >> 3);
                }
                if (auto_orbit_smooth > -8 && auto_orbit_smooth < 8)
                    auto_orbit_smooth = 0;
                orbit_angle += auto_orbit_smooth;
            }

            player_moving = (inputFwd || inputRight);

            if (player_moving)
            {
                // Track movement direction for sprite facing (brad atan2)
                player_move_angle = ArcTan2(inputRight, inputFwd);

                // Move player in world space using view direction
                FIXED moveFwd   = (inputFwd * moveSpeed) >> 8;
                FIXED moveRight = (inputRight * moveSpeed) >> 8;

                FIXED rightSin = lu_cos(viewAngle) >> 4;
                FIXED rightCos = -(lu_sin(viewAngle) >> 4);

                player_x += (viewSin * moveFwd + rightSin * moveRight) >> 8;
                player_z -= (viewCos * moveFwd + rightCos * moveRight) >> 8;
            }
            else if (wasMoving)
            {
                // Just stopped moving — freeze sprite direction relative to orbit
                player_move_angle = player_move_angle - orbit_angle;
            }

            // Clamp player to map bounds
            if (player_x < 0) player_x = 0;
            if (player_x > (256 << 8)) player_x = 256 << 8;
            if (player_z < 0) player_z = 0;
            if (player_z > (256 << 8)) player_z = 256 << 8;

            // Update sprite position
            g_sprites[player_sprite_idx].x = player_x;
            g_sprites[player_sprite_idx].z = player_z;

            // Place camera behind the player with smooth follow
            {
                FIXED orbSin = lu_sin(orbit_angle) >> 4;
                FIXED orbCos = lu_cos(orbit_angle) >> 4;
                FIXED targetX = player_x - ((orbSin * orbit_dist) >> 8);
                FIXED targetZ = player_z + ((orbCos * orbit_dist) >> 8);
                // Smooth follow using editor-configured ease rates
                FIXED ddx = targetX - cam_x;
                FIXED ddz = targetZ - cam_z;
                if (ddx > -16 && ddx < 16 && ddz > -16 && ddz < 16)
                { cam_x = targetX; cam_z = targetZ; }
                else
                {
#ifdef AFN_WALK_EASE_IN
                    int ease;
                    if (key_is_down(KEY_B))
                        ease = player_moving ? AFN_SPRINT_EASE_IN : AFN_SPRINT_EASE_OUT;
                    else
                        ease = player_moving ? AFN_WALK_EASE_IN : AFN_WALK_EASE_OUT;
                    // ease is pct*256/100; multiply delta by ease then >>8
                    cam_x += (ddx * ease) >> 8;
                    cam_z += (ddz * ease) >> 8;
#else
                    cam_x += (ddx * 3) >> 4;
                    cam_z += (ddz * 3) >> 4;
#endif
                }
            }
            cam_angle = orbit_angle;

            // DMA cycle direction animation frames — per-asset animation control
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
            {
                g_anim_frame_counter++;

                int ai;
                for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
                {
                    if (!afn_asset_dir_desc[ai][4]) continue;

                    // Only animate assets that have animation-enabled sprites
                    if (!g_asset_anim_enabled[ai])
                        continue;

                    // Determine target anim by game state mapping
                    // States: 0=None, 1=Idle, 2=Walk, 3=Run, 4=Sprint
                    {
                        int desiredState = 1; // Idle
                        if (player_moving)
                            desiredState = key_is_down(KEY_B) ? 4 : 2; // Sprint or Walk

                        int targetAnim = 0; // fallback to slot 0
#ifdef AFN_STATE_COUNT
                        {
                            int slot = afn_state_to_anim[ai][desiredState];
                            if (slot >= 0 && slot < AFN_MAX_ANIMS)
                                targetAnim = slot;
                            else
                            {
                                // Walk/Run fallback: try Run(3) if Walk(2) missing, vice versa
                                if (desiredState == 2) slot = afn_state_to_anim[ai][3];
                                else if (desiredState == 3) slot = afn_state_to_anim[ai][2];
                                if (slot >= 0 && slot < AFN_MAX_ANIMS) targetAnim = slot;
                            }
                        }
#endif
                        if (targetAnim != g_current_anim[ai])
                        {
                            g_current_anim[ai] = targetAnim;
                            g_anim_frame_counter = 0;
                        }
                    }

#ifdef AFN_MAX_ANIMS
                    if (g_current_anim[ai] >= AFN_MAX_ANIMS) continue;
                    {
                        int baseSet = afn_anim_desc[ai][g_current_anim[ai]][0];
                        int fc      = afn_anim_desc[ai][g_current_anim[ai]][1];
                        int fps     = afn_anim_desc[ai][g_current_anim[ai]][2];
                        if (fc <= 0) continue;
                        if (fps <= 0) fps = 8;
                        // Compute frame index from VBlank counter (60Hz / fps)
                        int framesPerTick = 60 / fps;
                        if (framesPerTick < 1) framesPerTick = 1;
                        int frame = (g_anim_frame_counter / framesPerTick) % fc;
                        int targetSet = baseSet + frame;
                        int setCount = afn_asset_dir_desc[ai][0];
                        if (targetSet < setCount)
                            switch_dir_anim_set(ai, targetSet);
                    }
#endif
                }
            }
#endif

        }
        else
        {
            // ============================================================
            // FREE CAMERA MODE (no player sprite — original controls)
            // ============================================================

            FIXED moveSpeed = 37;
            int   rotSpeed  = 0x0200;

            if (key_is_down(KEY_LEFT))
                cam_angle -= rotSpeed;
            if (key_is_down(KEY_RIGHT))
                cam_angle += rotSpeed;

            if (key_is_down(KEY_UP))
            {
                cam_x += (g_sinf * moveSpeed) >> 8;
                cam_z -= (g_cosf * moveSpeed) >> 8;
            }
            if (key_is_down(KEY_DOWN))
            {
                cam_x -= (g_sinf * moveSpeed) >> 8;
                cam_z += (g_cosf * moveSpeed) >> 8;
            }

            if (key_is_down(KEY_L) && cam_h > (4 << 8))
                cam_h -= 85;
            if (key_is_down(KEY_R) && cam_h < (256 << 8))
                cam_h += 85;

        }

        // Clamp camera to map bounds
        if (cam_x < 0) cam_x = 0;
        if (cam_x > (256 << 8)) cam_x = 256 << 8;
        if (cam_z < 0) cam_z = 0;
        if (cam_z > (256 << 8)) cam_z = 256 << 8;

        // Update sin/cos for HBlank
        g_cosf = lu_cos(cam_angle) >> 4;
        g_sinf = lu_sin(cam_angle) >> 4;

        // Reset to start position
        if (key_hit(KEY_START))
        {
            if (player_sprite_idx >= 0)
            {
                // Reset player and orbit
#if defined(AFN_PLAYER_IDX) && AFN_PLAYER_IDX >= 0
                player_x = g_sprites[AFN_PLAYER_IDX].x;
                player_z = g_sprites[AFN_PLAYER_IDX].z;
                // Reload original sprite positions
                load_editor_sprites();
                player_x = g_sprites[AFN_PLAYER_IDX].x;
                player_z = g_sprites[AFN_PLAYER_IDX].z;
                player_y = g_sprites[AFN_PLAYER_IDX].y;
#endif
                orbit_angle = AFN_CAM_ANGLE;
                player_moving = 0;
                player_move_angle = 0x4000; // face away from camera (show back)
            }
#ifdef AFFINITY_HAS_SPRITES
            cam_x     = AFN_CAM_X;
            cam_z     = AFN_CAM_Z;
            cam_h     = AFN_CAM_H;
            cam_angle = AFN_CAM_ANGLE;
            m7_horizon = AFN_CAM_HORIZON;
#else
            cam_x     = 128 << 8;
            cam_z     = 128 << 8;
            cam_h     = 14 << 8;
            cam_angle = 0;
            m7_horizon = 60;
#endif
        }

        // Project and draw sprites
        update_sprites();

        // Update minimap (not in mesh/bitmap mode — no BG0 available)
#if !defined(AFN_MESH_COUNT) || AFN_MESH_COUNT == 0
        update_minimap();
#endif
    }

    return 0;
}
