// Affinity GBA Runtime — Mode 7 floor with orbit camera + OAM sprites
// Built with devkitARM + libtonc

#include <tonc.h>
#include <string.h>

// ---------------------------------------------------------------------------
// Map data — generated by editor, or fallback checkerboard
// ---------------------------------------------------------------------------

#include "mapdata.h"

// ---------------------------------------------------------------------------
// Mode 7 state
// ---------------------------------------------------------------------------

// Camera (16.8 fixed-point for position, angle in brads)
static FIXED cam_x;
static FIXED cam_z;
static FIXED cam_h;        // height above floor
static u16   cam_angle;    // brad angle
static FIXED cam_fov;      // focal distance D

// Precomputed sin/cos for current angle
static FIXED g_cosf, g_sinf;

// Horizon scanline — variable for pitch control (A/B buttons)
static int m7_horizon = 60;

// ---------------------------------------------------------------------------
// Orbit camera state (used when player sprite exists)
// ---------------------------------------------------------------------------

static FIXED player_x, player_z;   // player world position (16.8)
static FIXED player_y;             // player height (16.8)
static u16   orbit_angle;          // brad angle of camera around player
static FIXED orbit_dist;           // distance from player (16.8)
static int   player_sprite_idx = -1;
static int   player_moving;        // nonzero if D-pad held
static u16   player_move_angle;    // brad angle of last movement direction
static int   auto_orbit_smooth;   // smoothed auto-orbit value (fixed-point)

// Direction animation set tracking (for DMA streaming)
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
static int   g_active_dir_set[AFN_ASSET_COUNT]; // currently loaded direction set per asset
static int   g_anim_frame_counter; // VBlank counter for animation frame cycling
static int   g_current_anim[AFN_ASSET_COUNT];  // per-asset: 0=idle, 1=run
static u8    g_asset_anim_enabled[AFN_ASSET_COUNT]; // per-asset: any sprite wants animation?
#endif

// ---------------------------------------------------------------------------
// Floor sprites — positions in 16.8 fixed-point
// ---------------------------------------------------------------------------

#define MAX_FLOOR_SPRITES 16

typedef struct {
    FIXED x;
    FIXED y;         // height above floor (16.8)
    FIXED z;
    u16   palIdx;    // OBJ palette color index
    s16   assetIdx;  // sprite asset index (-1 = default solid tile)
    FIXED scale;     // 8.8 fixed-point scale (256 = 1x)
    u16   rotation;  // world-space facing angle (brad, 0-65535)
    u8    animEnabled; // 0 = static, 1 = animate
    u8    spriteType;  // 0=Prop, 1=Player, 2=Enemy, etc.
} FloorSpriteGBA;

static FloorSpriteGBA g_sprites[MAX_FLOOR_SPRITES];
static int g_spriteCount = 0;

// Sprite projection result for sorting
typedef struct {
    int screenX;
    int screenY;
    int scale;    // 8.8 fixed-point scale (256 = 1x)
    int depth;    // for sorting (larger = farther)
    int idx;      // sprite index
} SpriteProjGBA;

// ---------------------------------------------------------------------------
// Mode 7 HBlank interrupt — per-scanline affine update
// ---------------------------------------------------------------------------

static void m7_hbl(void)
{
    int vc = REG_VCOUNT;

    // Above horizon: disable BG2 so backdrop color (sky) shows
    if (vc < m7_horizon)
    {
        REG_DISPCNT &= ~DCNT_BG2;
        return;
    }
    if (vc >= SCREEN_HEIGHT)
        return;

    // Re-enable BG2 at horizon
    REG_DISPCNT |= DCNT_BG2;

    // lambda = cam_height / (scanline - horizon)
    FIXED lam = cam_h * lu_div(vc - m7_horizon) >> 12;

    FIXED lcf = lam * g_cosf >> 8;
    FIXED lsf = lam * g_sinf >> 8;

    // Affine matrix — only PA and PC matter for per-scanline Mode 7
    REG_BG2PA =  lcf >> 4;
    REG_BG2PB = 0;
    REG_BG2PC =  lsf >> 4;
    REG_BG2PD = 0;

    // Reference point
    FIXED lxr, lyr;

    lxr = 120 * (lcf >> 4);
    lyr = cam_fov * (lsf >> 4);
    REG_BG2X = cam_x - lxr + lyr;

    lxr = 120 * (lsf >> 4);
    lyr = cam_fov * (lcf >> 4);
    REG_BG2Y = cam_z - lxr - lyr;
}

// ---------------------------------------------------------------------------
// Build checkerboard tiles + tilemap
// ---------------------------------------------------------------------------

static void load_checkerboard(void)
{
    pal_bg_mem[0] = RGB15(10, 16, 24);  // backdrop = sky blue
    pal_bg_mem[1] = RGB15(4, 10, 4);
    pal_bg_mem[2] = RGB15(8, 18, 8);
    pal_bg_mem[3] = RGB15(2, 6, 2);    // void/out-of-bounds dark green

    // Tile 0 = transparent (palette 0 = backdrop/sky blue) for out-of-bounds
    memset(&tile8_mem[2][0], 0, 64);

    // Tile 1 = 8x8 tile with internal 4x4 checkerboard sub-squares
    // This is the best balance: no Mode 7 stripe artifacts, close to editor size
    u8 *tile = (u8*)&tile8_mem[2][1];
    for (int py = 0; py < 8; py++)
        for (int px = 0; px < 8; px++)
            tile[py * 8 + px] = ((px / 4) + (py / 4)) & 1 ? 2 : 1;

    // Fill 64x64 map: checker tile within game world bounds (0-32 tiles)
    u8 *map = (u8*)se_mem[28];
    memset(map, 0, 64 * 64);  // default = tile 0 (void/transparent)
    for (int y = 0; y < 32; y++)
        for (int x = 0; x < 32; x++)
            map[y * 64 + x] = 1;
}

#ifdef AFFINITY_HAS_MAPDATA
static void load_editor_map(void)
{
    memcpy(&tile8_mem[2][0], afn_tiles, afn_tilesLen);
    memcpy(pal_bg_mem, afn_palette, afn_paletteLen);
    // Tile the 32x32 map into 64x64 (2x2 repeat) to match editor floor density
    u8 *map = (u8*)se_mem[28];
    const u8 *src = (const u8*)afn_tilemap;
    int y, x;
    for (y = 0; y < 64; y++)
        for (x = 0; x < 64; x++)
            map[y * 64 + x] = src[(y & 31) * 32 + (x & 31)];
}
#endif

// ---------------------------------------------------------------------------
// OBJ sprite setup
// ---------------------------------------------------------------------------

static void init_obj_sprites(void)
{
    int i;
    REG_DISPCNT |= DCNT_OBJ | DCNT_OBJ_1D;

#ifdef AFN_ASSET_COUNT
#if AFN_ASSET_COUNT > 0
    // Copy all asset tile data into OBJ VRAM (charblock 4)
    {
        const u32 *src = afn_all_tiles;
        u32 *dst = (u32*)tile_mem[4];
        for (i = 0; i < (int)(AFN_ALL_TILES_LEN / 4); i++)
            dst[i] = src[i];
    }

    // Load per-asset palettes into OBJ palette banks
    for (i = 0; i < AFN_ASSET_COUNT; i++)
    {
        int palBank = afn_asset_desc[i][4];
        const u16 *pal = 0;
        switch (i) {
            case 0: pal = afn_pal0; break;
#if AFN_ASSET_COUNT > 1
            case 1: pal = afn_pal1; break;
#endif
#if AFN_ASSET_COUNT > 2
            case 2: pal = afn_pal2; break;
#endif
#if AFN_ASSET_COUNT > 3
            case 3: pal = afn_pal3; break;
#endif
#if AFN_ASSET_COUNT > 4
            case 4: pal = afn_pal4; break;
#endif
#if AFN_ASSET_COUNT > 5
            case 5: pal = afn_pal5; break;
#endif
#if AFN_ASSET_COUNT > 6
            case 6: pal = afn_pal6; break;
#endif
#if AFN_ASSET_COUNT > 7
            case 7: pal = afn_pal7; break;
#endif
            default: break;
        }
        if (pal)
        {
            int c;
            for (c = 0; c < 16; c++)
                pal_obj_mem[palBank * 16 + c] = pal[c];
        }
    }

    // Init direction animation set tracking — DMA set 0 from ROM at boot
#if defined(AFN_HAS_ASSET_DIRS) && AFN_ASSET_COUNT > 0
    {
        int ai;
        for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
        {
            g_active_dir_set[ai] = -1; // mark as unloaded so switch_dir_anim_set works
            g_current_anim[ai] = 0;
            g_asset_anim_enabled[ai] = 0;
        }
        g_anim_frame_counter = 0;
    }
#endif

    // Load per-asset direction palettes if present
#ifdef AFN_HAS_ASSET_DIRS
    {
        int ai;
        for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
        {
            if (!afn_asset_dir_desc[ai][4]) continue; // no directions
            int adPalBank = afn_asset_dir_desc[ai][3];
            const u16 *adPal = 0;
            switch (ai) {
                case 0: adPal = afn_pal_assetdir0; break;
#if AFN_ASSET_COUNT > 1
                case 1: adPal = afn_pal_assetdir1; break;
#endif
#if AFN_ASSET_COUNT > 2
                case 2: adPal = afn_pal_assetdir2; break;
#endif
#if AFN_ASSET_COUNT > 3
                case 3: adPal = afn_pal_assetdir3; break;
#endif
                default: break;
            }
            if (adPal)
            {
                int c;
                for (c = 0; c < 16; c++)
                    pal_obj_mem[adPalBank * 16 + c] = adPal[c];
            }
        }
    }
#endif

#endif
#else
    // No assets — use fallback solid 8x8 tile
    {
        u32 *t0 = (u32*)&tile_mem[4][0];
        int k;
        for (k = 0; k < 8; k++) t0[k] = 0x11111111;
    }
    pal_obj_mem[1*16 + 1] = RGB15(31, 31, 0);
    pal_obj_mem[2*16 + 1] = RGB15(31, 8, 8);
    pal_obj_mem[3*16 + 1] = RGB15(8, 8, 31);
    pal_obj_mem[4*16 + 1] = RGB15(8, 31, 8);
    pal_obj_mem[5*16 + 1] = RGB15(31, 16, 31);
#endif

    // Minimap dot tile
    {
#ifdef AFN_MINIMAP_TILE
        u32 *dot = (u32*)&tile_mem[4][AFN_MINIMAP_TILE];
#else
        u32 *dot = (u32*)&tile_mem[4][16];
#endif
        int k;
        for (k = 0; k < 8; k++) dot[k] = 0;
        dot[0] = 0x00000011;
        dot[1] = 0x00000011;
    }

    // Minimap palette bank (bank 6)
    pal_obj_mem[6*16 + 0] = 0;
    pal_obj_mem[6*16 + 1] = RGB15(31, 31, 31);
    pal_obj_mem[6*16 + 2] = RGB15(20, 20, 20);
    pal_obj_mem[6*16 + 3] = RGB15(31, 0, 0);

    oam_init(obj_mem, 128);
}

// Place demo sprites if no editor data
static void init_demo_sprites(void)
{
    g_sprites[0].x = 160 << 8;
    g_sprites[0].y = 0;
    g_sprites[0].z = 128 << 8;
    g_sprites[0].palIdx = 1;
    g_sprites[0].assetIdx = -1;
    g_sprites[0].scale = 256;

    g_sprites[1].x = 96 << 8;
    g_sprites[1].y = 10 << 8;
    g_sprites[1].z = 96 << 8;
    g_sprites[1].palIdx = 2;
    g_sprites[1].assetIdx = -1;
    g_sprites[1].scale = 256;

    g_sprites[2].x = 160 << 8;
    g_sprites[2].y = 0;
    g_sprites[2].z = 64 << 8;
    g_sprites[2].palIdx = 3;
    g_sprites[2].assetIdx = -1;
    g_sprites[2].scale = 256;

    g_sprites[3].x = 64 << 8;
    g_sprites[3].y = 20 << 8;
    g_sprites[3].z = 160 << 8;
    g_sprites[3].palIdx = 4;
    g_sprites[3].assetIdx = -1;
    g_sprites[3].scale = 256;

    g_spriteCount = 4;
}

#ifdef AFFINITY_HAS_SPRITES
#if AFN_SPRITE_COUNT > 0
static void load_editor_sprites(void)
{
    int i;
    int count = AFN_SPRITE_COUNT;
    if (count > MAX_FLOOR_SPRITES) count = MAX_FLOOR_SPRITES;

    for (i = 0; i < count; i++)
    {
        g_sprites[i].x           = afn_sprite_data[i][0];
        g_sprites[i].y           = afn_sprite_data[i][1];
        g_sprites[i].z           = afn_sprite_data[i][2];
        g_sprites[i].palIdx      = afn_sprite_data[i][3];
        g_sprites[i].assetIdx    = afn_sprite_data[i][4];
        g_sprites[i].scale       = afn_sprite_data[i][5];
        g_sprites[i].rotation    = (u16)afn_sprite_data[i][7];
        g_sprites[i].animEnabled = (u8)afn_sprite_data[i][8];
        g_sprites[i].spriteType  = (u8)afn_sprite_data[i][6];
    }
    g_spriteCount = count;
}
#endif
#endif

// ---------------------------------------------------------------------------
// DMA direction animation set switching
// ---------------------------------------------------------------------------

#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
static void switch_dir_anim_set(int assetIdx, int newSet)
{
    if (assetIdx < 0 || assetIdx >= AFN_ASSET_COUNT) return;
    if (!afn_asset_dir_desc[assetIdx][4]) return; // no directions
    int setCount = afn_asset_dir_desc[assetIdx][0];
    if (newSet < 0 || newSet >= setCount) return;
    if (g_active_dir_set[assetIdx] == newSet) return; // already loaded

    int tpf = afn_asset_dir_desc[assetIdx][1];       // tiles per direction frame
    int vramTile0 = afn_asset_dir_desc[assetIdx][5];  // VRAM destination tile index
    int romOffset = afn_dir_set_offsets[assetIdx][newSet]; // u32 index into ROM array
    if (romOffset < 0) return;

    // Copy 8 directions * tpf tiles * 32 bytes/tile from ROM to VRAM
    int wordCount = 8 * tpf * 8; // 8 dirs * tpf tiles * 8 u32s per tile
    const u32 *src = &afn_dir_anim_tiles[romOffset];
    u32 *dst = (u32*)&tile_mem[4][vramTile0];

    // Use DMA3 for fast ROM→VRAM copy (runs at ~2 cycles per word)
    DMA_TRANSFER(dst, src, wordCount, 3, DMA_NOW | DMA_32);

    g_active_dir_set[assetIdx] = newSet;
}
#endif

// Map baseSize to GBA OBJ ATTR1_SIZE bits
static u16 size_to_attr1(int baseSize)
{
    switch (baseSize) {
        case 8:  return ATTR1_SIZE_8;
        case 16: return ATTR1_SIZE_16;
        case 64: return ATTR1_SIZE_64;
        default: return ATTR1_SIZE_32;
    }
}

// ---------------------------------------------------------------------------
// Project sprites to screen and update OAM
// ---------------------------------------------------------------------------

static void update_sprites(void)
{
    SpriteProjGBA proj[MAX_FLOOR_SPRITES];
    int projCount = 0;
    int i, j;
    SpriteProjGBA tmp;

    for (i = 0; i < g_spriteCount; i++)
    {
        FIXED dx = g_sprites[i].x - cam_x;
        FIXED dz = g_sprites[i].z - cam_z;

        FIXED fovLambda = (dx * g_sinf - dz * g_cosf) >> 8;
        FIXED side      = (dx * g_cosf + dz * g_sinf) >> 8;

        if (fovLambda <= 64) continue;

        FIXED heightDiff = cam_h - g_sprites[i].y;
        int screenY = m7_horizon + (int)((heightDiff * cam_fov) / fovLambda);
        int screenX = 120 + (int)((side * cam_fov) / fovLambda);

        int scale = (int)((cam_h * cam_fov) / fovLambda);

        // Use generous culling bounds (64x64 AFF_DBL = 128x128 canvas)
        if (screenY < -128 || screenY > 288) continue;
        if (screenX < -128 || screenX > 368) continue;
        if (scale < 1) continue;

        proj[projCount].screenX = screenX;
        proj[projCount].screenY = screenY;
        proj[projCount].scale   = scale;
        proj[projCount].depth   = fovLambda;
        proj[projCount].idx     = i;
        projCount++;
    }

    // Sort front-to-back
    for (i = 0; i < projCount - 1; i++)
        for (j = i + 1; j < projCount; j++)
            if (proj[i].depth > proj[j].depth)
            {
                tmp = proj[i];
                proj[i] = proj[j];
                proj[j] = tmp;
            }

    // Render projected sprites as affine OBJs
    for (i = 0; i < projCount && i < 16; i++)
    {
        int oamIdx = 16 + i;
        int affIdx = i;
        int sprIdx = proj[i].idx;
        int palBank = g_sprites[sprIdx].palIdx;
        int tileId = 0;
        int baseSize = 32; // default for player dir sprites
        int scaleSize = 32; // size used for scale calculation (asset's original frame size)

        // Resolve tile/palette from asset (both player and non-player sprites)
        {
#ifdef AFN_ASSET_COUNT
#if AFN_ASSET_COUNT > 0
            {
                int ai = g_sprites[sprIdx].assetIdx;
                if (ai >= 0 && ai < AFN_ASSET_COUNT)
                {
                    scaleSize = afn_asset_desc[ai][3];
#ifdef AFN_HAS_ASSET_DIRS
                    // Check if this asset has directional sprites
                    if (afn_asset_dir_desc[ai][4])
                    {
                        int dirIdx;
                        if (sprIdx == player_sprite_idx)
                        {
                            // Player direction: based on movement/orbit angle (NOT camera-to-sprite)
                            u16 sprAngle;
                            if (player_moving)
                                sprAngle = player_move_angle;
                            else
                                sprAngle = orbit_angle + player_move_angle;
                            int rawIdx = ((sprAngle + 0xC000 + 4096) >> 13) & 7;
                            dirIdx = (8 - rawIdx) & 7;
                        }
                        else
                        {
                            // Non-player: compute angle from camera to sprite
                            FIXED dx = g_sprites[sprIdx].x - cam_x;
                            FIXED dz = g_sprites[sprIdx].z - cam_z;
                            u16 angleToSprite = ArcTan2(dx >> 4, -(dz >> 4));
                            u16 relAngle = angleToSprite + 0x4000 - g_sprites[sprIdx].rotation;
                            dirIdx = ((relAngle + 0x1000) >> 13) & 7;
                        }
                        {
                            int adTpf = afn_asset_dir_desc[ai][1];
                            int vramTile0 = afn_asset_dir_desc[ai][5];
                            tileId = vramTile0 + dirIdx * adTpf;
                            baseSize = afn_asset_dir_desc[ai][2];
                            scaleSize = baseSize; // use direction size for scaling
                            palBank = afn_asset_dir_desc[ai][3];
                        }
                    }
                    else
#endif
                    {
                        tileId = afn_asset_desc[ai][0];
                        baseSize = afn_asset_desc[ai][3];
                        palBank = afn_asset_desc[ai][4];
                    }
                }
            }
#endif
#endif
        }

        if (palBank > 15) palBank = 1;

        // Skip sprites with no valid asset (prevents rogue pixels)
        if (g_sprites[sprIdx].assetIdx < 0)
        {
            obj_mem[16 + i].attr0 = ATTR0_HIDE;
            continue;
        }

        {
            int sprScale = g_sprites[sprIdx].scale;
            int invScale;
            int canvasHalf = baseSize; // AFF_DBL canvas = 2 * baseSize
            if (sprScale <= 0) sprScale = 256;

            // Scale based on scaleSize (asset's original frame size) so direction
            // sprites (64x64) appear the same on-screen size as regular frames (32x32)
            invScale = (proj[i].depth * 14 * baseSize) / (sprScale * scaleSize);
            // invScale=128 means 2x magnification, which exactly fills the
            // AFF_DBL canvas (2*baseSize).  Going lower clips the sprite.
            if (invScale < 128) invScale = 128;
            if (invScale > 2048) invScale = 2048;

            obj_aff_mem[affIdx].pa = (s16)invScale;
            obj_aff_mem[affIdx].pb = 0;
            obj_aff_mem[affIdx].pc = 0;
            obj_aff_mem[affIdx].pd = (s16)invScale;

            int visHalf = (baseSize * 128) / invScale;
            int sx = proj[i].screenX - canvasHalf;
            int sy = proj[i].screenY - canvasHalf - visHalf;

            obj_mem[oamIdx].attr0 = ATTR0_Y(sy & 0xFF) | ATTR0_SQUARE | ATTR0_AFF_DBL;
            obj_mem[oamIdx].attr1 = ATTR1_X(sx & 0x1FF) | size_to_attr1(baseSize) | ATTR1_AFF_ID(affIdx);
            obj_mem[oamIdx].attr2 = ATTR2_ID(tileId) | ATTR2_PRIO(0) | ATTR2_PALBANK(palBank);
        }
    }

    // Hide remaining floor sprite OBJ slots
    for (; i < 16; i++)
    {
        obj_mem[16 + i].attr0 = ATTR0_HIDE;
    }
}

// ---------------------------------------------------------------------------
// Minimap
// ---------------------------------------------------------------------------

#define MINIMAP_X  4
#define MINIMAP_Y  124
#define MINIMAP_W  32
#define MINIMAP_H  32

#define TILE_MINIMAP_BG    1
#define TILE_MINIMAP_GRID  2
#define TILE_MINIMAP_CAM   3

static void init_minimap(void)
{
    REG_BG0CNT = BG_CBB(0) | BG_SBB(30) | BG_4BPP | BG_REG_32x32 | BG_PRIO(0);

    pal_bg_mem[16 + 0] = 0;
    pal_bg_mem[16 + 1] = RGB15(2, 4, 2);
    pal_bg_mem[16 + 2] = RGB15(5, 10, 5);
    pal_bg_mem[16 + 3] = RGB15(31, 31, 31);

    {
        u32 *t = (u32*)&tile_mem[0][TILE_MINIMAP_BG];
        int k;
        for (k = 0; k < 8; k++)
            t[k] = 0x11111111;
    }

    {
        u32 *t = (u32*)&tile_mem[0][TILE_MINIMAP_GRID];
        int k;
        t[0] = 0x22222222;
        for (k = 1; k < 7; k++)
            t[k] = 0x11111112;
        t[7] = 0x22222222;
    }

    {
        u16 *map = (u16*)se_mem[30];
        int k;
        for (k = 0; k < 32*32; k++)
            map[k] = 0;
    }

    {
        u16 *map = (u16*)se_mem[30];
        int tx, ty;
        for (ty = 0; ty < 4; ty++)
            for (tx = 0; tx < 4; tx++)
                map[ty * 32 + tx] = TILE_MINIMAP_GRID | SE_PALBANK(1);
    }

    REG_BG0HOFS = (512 - MINIMAP_X) & 0x1FF;
    REG_BG0VOFS = (512 - MINIMAP_Y) & 0x1FF;
}

static void update_minimap(void)
{
    int i;
    int oamIdx = 0;

    // Camera/player position dot
    FIXED dotX = (player_sprite_idx >= 0) ? player_x : cam_x;
    FIXED dotZ = (player_sprite_idx >= 0) ? player_z : cam_z;

    int camMX = MINIMAP_X + ((dotX >> 8) >> 3);
    int camMY = MINIMAP_Y + ((dotZ >> 8) >> 3);

    if (camMX < MINIMAP_X) camMX = MINIMAP_X;
    if (camMX > MINIMAP_X + MINIMAP_W - 1) camMX = MINIMAP_X + MINIMAP_W - 1;
    if (camMY < MINIMAP_Y) camMY = MINIMAP_Y;
    if (camMY > MINIMAP_Y + MINIMAP_H - 1) camMY = MINIMAP_Y + MINIMAP_H - 1;

    {
#ifdef AFN_MINIMAP_TILE
        int dotTile = AFN_MINIMAP_TILE;
#else
        int dotTile = 16;
#endif
        obj_mem[oamIdx].attr0 = ATTR0_Y(camMY & 0xFF) | ATTR0_SQUARE;
        obj_mem[oamIdx].attr1 = ATTR1_X(camMX & 0x1FF) | ATTR1_SIZE_8;
        obj_mem[oamIdx].attr2 = ATTR2_ID(dotTile) | ATTR2_PRIO(0) | ATTR2_PALBANK(6);
    }
    oamIdx++;

    for (i = 0; i < g_spriteCount && oamIdx < 16; i++)
    {
        if (i == player_sprite_idx) continue; // player already shown as main dot
        int smx = MINIMAP_X + ((g_sprites[i].x >> 8) >> 3);
        int smy = MINIMAP_Y + ((g_sprites[i].z >> 8) >> 3);

        if (smx < MINIMAP_X || smx > MINIMAP_X + MINIMAP_W - 1) continue;
        if (smy < MINIMAP_Y || smy > MINIMAP_Y + MINIMAP_H - 1) continue;

        int palBank = g_sprites[i].palIdx;
        if (palBank > 5) palBank = 1;

        {
#ifdef AFN_MINIMAP_TILE
            int dotTile = AFN_MINIMAP_TILE;
#else
            int dotTile = 16;
#endif
            obj_mem[oamIdx].attr0 = ATTR0_Y(smy & 0xFF) | ATTR0_SQUARE;
            obj_mem[oamIdx].attr1 = ATTR1_X(smx & 0x1FF) | ATTR1_SIZE_8;
            obj_mem[oamIdx].attr2 = ATTR2_ID(dotTile) | ATTR2_PRIO(0) | ATTR2_PALBANK(palBank);
        }
        oamIdx++;
    }

    for (; oamIdx < 16; oamIdx++)
    {
        obj_mem[oamIdx].attr0 = ATTR0_HIDE;
    }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

int main(void)
{
    // --- Video setup ---
    REG_DISPCNT = DCNT_MODE1 | DCNT_BG0 | DCNT_BG2;

    REG_BG2CNT = BG_CBB(2) | BG_SBB(28) | BG_AFF_64x64 | BG_8BPP;

    REG_BG2PA = 0x0100;
    REG_BG2PB = 0;
    REG_BG2PC = 0;
    REG_BG2PD = 0x0100;
    REG_BG2X  = 0;
    REG_BG2Y  = 0;

    // --- Load map data ---
#ifdef AFFINITY_HAS_MAPDATA
    load_editor_map();
#else
    load_checkerboard();
#endif

    // --- OBJ sprite setup ---
    init_obj_sprites();

    // DMA direction animation set 0 from ROM to VRAM at boot
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
    {
        int ai;
        for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
        {
            if (!afn_asset_dir_desc[ai][4]) continue;
            switch_dir_anim_set(ai, 0);
        }
    }
#endif

    // --- Minimap setup ---
    init_minimap();

#if defined(AFFINITY_HAS_SPRITES) && AFN_SPRITE_COUNT > 0
    load_editor_sprites();
#else
    #ifndef AFFINITY_HAS_MAPDATA
    init_demo_sprites();
    #endif
#endif

    // Determine which assets have animation-enabled sprites (must be after load_editor_sprites)
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
#if defined(AFN_SPRITE_COUNT) && AFN_SPRITE_COUNT > 0
    {
        int si;
        for (si = 0; si < g_spriteCount; si++)
        {
            int aidx = g_sprites[si].assetIdx;
            if (aidx >= 0 && aidx < AFN_ASSET_COUNT && g_sprites[si].animEnabled
                && g_sprites[si].spriteType == 1) // 1 = Player
                g_asset_anim_enabled[aidx] = 1;
        }
    }
#endif
#endif

    // --- Camera init ---
#ifdef AFFINITY_HAS_SPRITES
    cam_x     = AFN_CAM_X;
    cam_z     = AFN_CAM_Z;
    cam_h     = AFN_CAM_H;
    cam_angle = AFN_CAM_ANGLE;
    cam_fov   = 128;
    m7_horizon = AFN_CAM_HORIZON;
#else
    cam_x     = 128 << 8;
    cam_z     = 128 << 8;
    cam_h     = 14 << 8;
    cam_angle = 0;
    cam_fov   = 128;
#endif

    // --- Orbit camera init ---
    player_sprite_idx = -1;
#if defined(AFN_PLAYER_IDX) && AFN_PLAYER_IDX >= 0
    player_sprite_idx = AFN_PLAYER_IDX;
    player_x = g_sprites[AFN_PLAYER_IDX].x;
    player_z = g_sprites[AFN_PLAYER_IDX].z;
    player_y = g_sprites[AFN_PLAYER_IDX].y;
    orbit_angle = AFN_CAM_ANGLE;
    orbit_dist = AFN_ORBIT_DIST;
    player_moving = 0;
    player_move_angle = 0x4000; // face away from camera (show back)
#endif

    // Precompute initial sin/cos
    g_cosf = lu_cos(cam_angle) >> 4;
    g_sinf = lu_sin(cam_angle) >> 4;

    // --- Set up HBlank interrupt ---
    irq_init(NULL);
    irq_add(II_VBLANK, NULL);
    irq_add(II_HBLANK, m7_hbl);

    // --- Main loop ---
    while (1)
    {
        VBlankIntrWait();
        REG_DISPCNT &= ~DCNT_BG2;
        key_poll();

        if (player_sprite_idx >= 0)
        {
            // ============================================================
            // ORBIT CAMERA MODE — Asterix XXL style
            // ============================================================

            FIXED moveSpeed = 37;
            int   rotSpeed  = 0x0200;

            // View angle = orbit_angle (camera is behind player, looking forward)
            u16 viewAngle = orbit_angle;
            FIXED viewSin = lu_sin(viewAngle) >> 4;
            FIXED viewCos = lu_cos(viewAngle) >> 4;

            // D-pad = player movement
            FIXED inputFwd = 0, inputRight = 0;
            if (key_is_down(KEY_UP))    inputFwd   += 256;
            if (key_is_down(KEY_DOWN))  inputFwd   -= 256;
            if (key_is_down(KEY_LEFT))  inputRight -= 256;
            if (key_is_down(KEY_RIGHT)) inputRight += 256;

            // Normalize diagonal (~0.707)
            if (inputFwd && inputRight)
            {
                inputFwd   = (inputFwd * 181) >> 8;
                inputRight = (inputRight * 181) >> 8;
            }

            int wasMoving = player_moving;
            player_moving = (inputFwd || inputRight);

            // L/R shoulder = manual orbit (always applies)
            if (key_is_down(KEY_L))
                orbit_angle -= rotSpeed;
            if (key_is_down(KEY_R))
                orbit_angle += rotSpeed;

            // Auto-orbit when strafing (LEFT/RIGHT) with drag on release
            {
                int autoOrbitTarget = 0;
                if (inputRight)
                {
                    autoOrbitTarget = (rotSpeed * 2 / 5);  // 40% of rotSpeed
                    if (inputRight < 0)
                        autoOrbitTarget = -autoOrbitTarget;
                    if (key_is_down(KEY_L) || key_is_down(KEY_R))
                        autoOrbitTarget *= 2;
                }
                if (autoOrbitTarget != 0)
                    auto_orbit_smooth += (autoOrbitTarget - auto_orbit_smooth) >> 2;
                else
                {
                    // Decay toward zero (handle negative values correctly)
                    if (auto_orbit_smooth > 0)
                        auto_orbit_smooth = (auto_orbit_smooth * 7) >> 3;  // ~0.875 decay
                    else if (auto_orbit_smooth < 0)
                        auto_orbit_smooth = -(((-auto_orbit_smooth) * 7) >> 3);
                }
                if (auto_orbit_smooth > -8 && auto_orbit_smooth < 8)
                    auto_orbit_smooth = 0;
                orbit_angle += auto_orbit_smooth;
            }

            if (player_moving)
            {
                // Track movement direction for sprite facing (brad atan2)
                player_move_angle = ArcTan2(inputRight, inputFwd);

                // Move player in world space using view direction
                FIXED moveFwd   = (inputFwd * moveSpeed) >> 8;
                FIXED moveRight = (inputRight * moveSpeed) >> 8;

                FIXED rightSin = lu_cos(viewAngle) >> 4;
                FIXED rightCos = -(lu_sin(viewAngle) >> 4);

                player_x += (viewSin * moveFwd + rightSin * moveRight) >> 8;
                player_z -= (viewCos * moveFwd + rightCos * moveRight) >> 8;
            }
            else if (wasMoving)
            {
                // Just stopped moving — freeze sprite direction relative to orbit
                player_move_angle = player_move_angle - orbit_angle;
            }

            // Clamp player to map bounds
            if (player_x < 0) player_x = 0;
            if (player_x > (256 << 8)) player_x = 256 << 8;
            if (player_z < 0) player_z = 0;
            if (player_z > (256 << 8)) player_z = 256 << 8;

            // Update sprite position
            g_sprites[player_sprite_idx].x = player_x;
            g_sprites[player_sprite_idx].z = player_z;

            // Place camera behind the player with smooth follow
            {
                FIXED orbSin = lu_sin(orbit_angle) >> 4;
                FIXED orbCos = lu_cos(orbit_angle) >> 4;
                FIXED targetX = player_x - ((orbSin * orbit_dist) >> 8);
                FIXED targetZ = player_z + ((orbCos * orbit_dist) >> 8);
                // Smooth follow: blend 3/8 toward target each frame
                FIXED ddx = targetX - cam_x;
                FIXED ddz = targetZ - cam_z;
                if (ddx > -16 && ddx < 16 && ddz > -16 && ddz < 16)
                { cam_x = targetX; cam_z = targetZ; }
                else
                { cam_x += (ddx * 3) >> 4; cam_z += (ddz * 3) >> 4; }
            }
            cam_angle = orbit_angle;

            // DMA cycle direction animation frames — per-asset animation control
#if defined(AFN_HAS_ASSET_DIRS) && defined(AFN_ASSET_COUNT) && AFN_ASSET_COUNT > 0
            {
                g_anim_frame_counter++;

                int ai;
                for (ai = 0; ai < AFN_ASSET_COUNT; ai++)
                {
                    if (!afn_asset_dir_desc[ai][4]) continue;

                    // Only animate assets that have animation-enabled sprites
                    if (!g_asset_anim_enabled[ai])
                        continue;

                    // Determine target anim for this asset based on player movement
                    int targetAnim = player_moving ? 1 : 0;
                    if (targetAnim != g_current_anim[ai])
                    {
                        g_current_anim[ai] = targetAnim;
                        // Reset frame counter on anim switch (per-asset reset would need per-asset counters,
                        // but shared counter is fine since all animated assets switch together)
                    }

#ifdef AFN_MAX_ANIMS
                    if (g_current_anim[ai] >= AFN_MAX_ANIMS) continue;
                    {
                        int baseSet = afn_anim_desc[ai][g_current_anim[ai]][0];
                        int fc      = afn_anim_desc[ai][g_current_anim[ai]][1];
                        int fps     = afn_anim_desc[ai][g_current_anim[ai]][2];
                        if (fc <= 0) continue;
                        if (fps <= 0) fps = 8;
                        // Compute frame index from VBlank counter (60Hz / fps)
                        int framesPerTick = 60 / fps;
                        if (framesPerTick < 1) framesPerTick = 1;
                        int frame = (g_anim_frame_counter / framesPerTick) % fc;
                        int targetSet = baseSet + frame;
                        int setCount = afn_asset_dir_desc[ai][0];
                        if (targetSet < setCount)
                            switch_dir_anim_set(ai, targetSet);
                    }
#endif
                }
            }
#endif

        }
        else
        {
            // ============================================================
            // FREE CAMERA MODE (no player sprite — original controls)
            // ============================================================

            FIXED moveSpeed = 37;
            int   rotSpeed  = 0x0200;

            if (key_is_down(KEY_LEFT))
                cam_angle -= rotSpeed;
            if (key_is_down(KEY_RIGHT))
                cam_angle += rotSpeed;

            if (key_is_down(KEY_UP))
            {
                cam_x += (g_sinf * moveSpeed) >> 8;
                cam_z -= (g_cosf * moveSpeed) >> 8;
            }
            if (key_is_down(KEY_DOWN))
            {
                cam_x -= (g_sinf * moveSpeed) >> 8;
                cam_z += (g_cosf * moveSpeed) >> 8;
            }

            if (key_is_down(KEY_L) && cam_h > (4 << 8))
                cam_h -= 85;
            if (key_is_down(KEY_R) && cam_h < (256 << 8))
                cam_h += 85;

        }

        // Clamp camera to map bounds
        if (cam_x < 0) cam_x = 0;
        if (cam_x > (256 << 8)) cam_x = 256 << 8;
        if (cam_z < 0) cam_z = 0;
        if (cam_z > (256 << 8)) cam_z = 256 << 8;

        // Update sin/cos for HBlank
        g_cosf = lu_cos(cam_angle) >> 4;
        g_sinf = lu_sin(cam_angle) >> 4;

        // Reset to start position
        if (key_hit(KEY_START))
        {
            if (player_sprite_idx >= 0)
            {
                // Reset player and orbit
#if defined(AFN_PLAYER_IDX) && AFN_PLAYER_IDX >= 0
                player_x = g_sprites[AFN_PLAYER_IDX].x;
                player_z = g_sprites[AFN_PLAYER_IDX].z;
                // Reload original sprite positions
                load_editor_sprites();
                player_x = g_sprites[AFN_PLAYER_IDX].x;
                player_z = g_sprites[AFN_PLAYER_IDX].z;
                player_y = g_sprites[AFN_PLAYER_IDX].y;
#endif
                orbit_angle = AFN_CAM_ANGLE;
                player_moving = 0;
                player_move_angle = 0x4000; // face away from camera (show back)
            }
#ifdef AFFINITY_HAS_SPRITES
            cam_x     = AFN_CAM_X;
            cam_z     = AFN_CAM_Z;
            cam_h     = AFN_CAM_H;
            cam_angle = AFN_CAM_ANGLE;
            m7_horizon = AFN_CAM_HORIZON;
#else
            cam_x     = 128 << 8;
            cam_z     = 128 << 8;
            cam_h     = 14 << 8;
            cam_angle = 0;
            m7_horizon = 60;
#endif
        }

        // Project and draw sprites
        update_sprites();

        // Update minimap
        update_minimap();
    }

    return 0;
}
