// Affinity PSP exporter — generates psp_runtime/include/psp_mapdata.h (float
// geometry + RGBA8888 textures) and builds EBOOT.PBP via the pspdev toolchain
// (invoked through WSL, since pspdev ships Linux binaries).
//
// First pass scope: the Mode 4 3D scene — meshes, mesh instances (sprites that
// reference a mesh), camera start, and textures. Sprites/HUD/scripts/sound are
// accepted in the signature and ignored for now (filled in over later passes).
//
// World units: "world px" = editorCoord/4, with a +512 offset on X/Z (matches
// the NDS exporter's EditorToFixed minus the 8.8 fixed-point shift), so the PSP
// scene proportions line up with what the editor/NDS show.

#include "psp_package.h"

#include <fstream>
#include <sstream>
#include <cmath>
#include <cstdio>

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#endif

namespace Affinity {

// ---- helpers --------------------------------------------------------------
static std::string ToWslPath(const std::string& winPath) {
    // C:\a\b -> /mnt/c/a/b
    std::string p = winPath;
    for (auto& c : p) if (c == '\\') c = '/';
    if (p.size() >= 2 && p[1] == ':') {
        char drive = (char)tolower(p[0]);
        p = "/mnt/" + std::string(1, drive) + p.substr(2);
    }
    return p;
}

#ifdef _WIN32
// Run a command inside WSL, capturing stdout+stderr. Returns exit code, or -1
// if WSL itself couldn't be launched.
static int RunWslCommand(const std::string& shellCmd, std::string& output) {
    HANDLE hRead, hWrite;
    SECURITY_ATTRIBUTES sa = { sizeof(sa), nullptr, TRUE };
    if (!CreatePipe(&hRead, &hWrite, &sa, 0)) return -1;
    SetHandleInformation(hRead, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si = {}; si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdOutput = hWrite; si.hStdError = hWrite;
    si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);

    PROCESS_INFORMATION pi = {};
    std::string cmdLine = "wsl.exe bash -lc \"" + shellCmd + "\"";
    BOOL ok = CreateProcessA(nullptr, (LPSTR)cmdLine.c_str(), nullptr, nullptr,
                             TRUE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi);
    CloseHandle(hWrite);
    if (!ok) { CloseHandle(hRead); output = "Failed to launch WSL (is it installed?)"; return -1; }

    output.clear();
    char buf[512]; DWORD n;
    while (ReadFile(hRead, buf, sizeof(buf) - 1, &n, nullptr) && n > 0) { buf[n] = 0; output += buf; }
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD code = 1; GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hProcess); CloseHandle(pi.hThread); CloseHandle(hRead);
    return (int)code;
}
#else
static int RunWslCommand(const std::string&, std::string& output) { output = "WSL build only supported on Windows host"; return -1; }
#endif

// editor coords -> PSP world px
static float WX(float e) { return (e + 512.0f) / 4.0f; }   // X/Z
static float WY(float h) { return h / 4.0f; }               // height
static float WL(float p) { return p / 4.0f; }               // mesh-local

// Format a float as a valid C float literal. Default stream formatting drops
// the decimal point on whole numbers ("128"), and "128f" is not a valid
// literal — so ensure a '.' (or exponent) is present before the 'f' suffix.
static std::string Flt(float v) {
    char buf[40];
    snprintf(buf, sizeof(buf), "%.6g", v);
    std::string s = buf;
    if (s.find_first_of(".eEnN") == std::string::npos) s += ".0";
    return s + "f";
}

// RGB15 (5/5/5, index from texPalette) -> 0xAABBGGRR (PSP GU_PSM_8888)
static unsigned int Rgb15ToAbgr(unsigned short c, bool opaque) {
    unsigned r5 = c & 0x1F, g5 = (c >> 5) & 0x1F, b5 = (c >> 10) & 0x1F;
    unsigned r = (r5 << 3) | (r5 >> 2);
    unsigned g = (g5 << 3) | (g5 >> 2);
    unsigned b = (b5 << 3) | (b5 >> 2);
    unsigned a = opaque ? 0xFF : 0x00;
    return (a << 24) | (b << 16) | (g << 8) | r;
}

// ---- header generation ----------------------------------------------------
static bool GeneratePSPMapData(const std::string& runtimeDir,
                               const std::vector<GBASpriteExport>& sprites,
                               const GBACameraExport& camera,
                               const std::vector<GBAMeshExport>& meshes,
                               float orbitDist,
                               std::string& errorMsg) {
    std::string path = runtimeDir + "\\include\\psp_mapdata.h";
    std::ofstream f(path);
    if (!f) { errorMsg = "Could not open " + path + " for writing"; return false; }

    f << "// Affinity PSP scene data — GENERATED by Export PSP. Do not edit.\n";
    f << "#pragma once\n#include \"affinity_psp.h\"\n\n";

    // ---- meshes ----
    for (size_t mi = 0; mi < meshes.size(); mi++) {
        const auto& m = meshes[mi];
        int vc = (int)m.positions.size() / 3;
        bool textured = m.textured && m.texW > 0 && !m.texPixels.empty();
        bool opaqueTex = !m.textureHasAlpha;

        // Vertices (interleaved AfnVertex).
        f << "static const AfnVertex afn_mesh" << mi << "_verts[" << (vc > 0 ? vc : 1) << "] = {\n";
        for (int v = 0; v < vc; v++) {
            float u = 0.0f, vv = 0.0f;
            if (textured && (int)m.uvs.size() >= (v + 1) * 2) {
                u = m.uvs[v*2+0];
                // Flip V: UVs are authored bottom-origin (glTF/OBJ), but the GE
                // samples top-origin — same 1-v the NDS exporter applies. Without
                // this, V is upside-down (terrain hits the atlas's black bottom).
                vv = 1.0f - m.uvs[v*2+1];
            }
            unsigned int col;
            if (m.hasVertexColor && (int)m.vertexColors.size() >= (v + 1) * 3) {
                unsigned r = m.vertexColors[v*3+0], g = m.vertexColors[v*3+1], b = m.vertexColors[v*3+2];
                col = 0xFF000000u | (b << 16) | (g << 8) | r;
            } else if (textured) {
                col = 0xFFFFFFFFu;   // modulate texture unchanged
            } else {
                col = Rgb15ToAbgr(m.colorRGB15, true);
            }
            f << "  {" << Flt(u) << "," << Flt(vv) << ",0x" << std::hex << col << std::dec << "u,"
              << Flt(WL(m.positions[v*3+0])) << "," << Flt(WL(m.positions[v*3+1])) << "," << Flt(WL(m.positions[v*3+2])) << "},\n";
        }
        if (vc == 0) f << "  {0,0,0xFFFFFFFFu,0,0,0},\n";
        f << "};\n";

        // Indices: triangles + triangulated quads.
        std::vector<unsigned int> idx = m.indices;
        for (size_t q = 0; q + 4 <= m.quadIndices.size(); q += 4) {
            unsigned a = m.quadIndices[q], b = m.quadIndices[q+1], c = m.quadIndices[q+2], d = m.quadIndices[q+3];
            idx.push_back(a); idx.push_back(b); idx.push_back(c);
            idx.push_back(a); idx.push_back(c); idx.push_back(d);
        }
        f << "static const unsigned short afn_mesh" << mi << "_idx[" << (idx.empty() ? 1 : idx.size()) << "] = {";
        for (size_t k = 0; k < idx.size(); k++) { if (k % 16 == 0) f << "\n  "; f << idx[k] << ","; }
        if (idx.empty()) f << "0,";
        f << "\n};\n";

        // Texture (RGBA8888). 16-byte aligned: the GE masks the low bits of the
        // texture base address, so an unaligned texture samples wrong/empty
        // memory (black) on real hardware (PPSSPP is more forgiving).
        if (textured) {
            int n = m.texW * m.texH;
            f << "static const unsigned int __attribute__((aligned(16))) afn_mesh" << mi << "_tex[" << n << "] = {";
            for (int p = 0; p < n; p++) {
                if (p % 8 == 0) f << "\n  ";
                unsigned char pi = (p < (int)m.texPixels.size()) ? m.texPixels[p] : 0;
                bool opaque = opaqueTex || pi != 0;        // index 0 transparent when alpha on
                unsigned short pal = m.texPalette[pi];
                f << "0x" << std::hex << Rgb15ToAbgr(pal, opaque) << std::dec << "u,";
            }
            f << "\n};\n";
        }
        f << "\n";
    }

    // ---- mesh table ----
    f << "const int afn_mesh_count = " << meshes.size() << ";\n";
    f << "const AfnMesh afn_meshes[" << (meshes.empty() ? 1 : meshes.size()) << "] = {\n";
    for (size_t mi = 0; mi < meshes.size(); mi++) {
        const auto& m = meshes[mi];
        int vc = (int)m.positions.size() / 3;
        int ic = (int)m.indices.size() + (int)(m.quadIndices.size() / 4) * 6;
        bool textured = m.textured && m.texW > 0 && !m.texPixels.empty();
        f << "  { " << vc << ", " << ic << ", afn_mesh" << mi << "_verts, afn_mesh" << mi << "_idx, "
          << (textured ? 1 : 0) << ", " << (textured ? m.texW : 0) << ", " << (textured ? m.texH : 0) << ", "
          << (textured ? std::string("afn_mesh") + std::to_string(mi) + "_tex" : std::string("0")) << ", "
          << (m.textureHasAlpha ? 1 : 0) << ", " << m.cullMode << ", " << m.lit << ", " << m.visible << " },\n";
    }
    if (meshes.empty()) f << "  { 0,0,0,0,0,0,0,0,0,2,0,0 },\n";
    f << "};\n\n";

    // ---- mesh instances (sprites that carry a mesh) ----
    std::vector<size_t> inst;
    for (size_t i = 0; i < sprites.size(); i++) if (sprites[i].meshIdx >= 0) inst.push_back(i);
    f << "const int afn_sprite_count = " << inst.size() << ";\n";
    f << "const AfnSpriteInst afn_sprites[" << (inst.empty() ? 1 : inst.size()) << "] = {\n";
    for (size_t k = 0; k < inst.size(); k++) {
        const auto& s = sprites[inst[k]];
        f << "  { " << Flt(WX(s.x)) << ", " << Flt(WY(s.y)) << ", " << Flt(WX(s.z)) << ", "
          << Flt(s.scale) << ", " << Flt(s.rotation) << ", " << Flt(s.rotationX) << ", " << Flt(s.rotationZ) << ", "
          << s.meshIdx << " },\n";
    }
    if (inst.empty()) f << "  { 0,0,0,1,0,0,0,-1 },\n";
    f << "};\n\n";

    // ---- camera / movement ----
    f << "const float afn_cam_start_x = " << Flt(WX(camera.x)) << ";\n";
    f << "const float afn_cam_start_z = " << Flt(WX(camera.z)) << ";\n";
    f << "const float afn_cam_start_h = " << Flt(WY(camera.height)) << ";\n";
    f << "const float afn_cam_start_angle = " << Flt(camera.angle) << ";\n";
    f << "const float afn_orbit_dist = " << Flt(orbitDist / 4.0f) << ";\n";
    f << "const float afn_draw_distance = " << Flt(camera.drawDistance > 0 ? camera.drawDistance / 4.0f : 0.0f) << ";\n";
    f << "const float afn_walk_speed = " << Flt(camera.walkSpeed) << ";\n";
    f << "const float afn_sprint_speed = " << Flt(camera.sprintSpeed) << ";\n";

    f.close();
    return true;
}

// ---- public entry ---------------------------------------------------------
bool PackagePSP(const std::string& runtimeDir,
                const std::string& outputPath,
                const std::vector<GBASpriteExport>& sprites,
                const std::vector<GBASpriteAssetExport>& /*assets*/,
                const GBACameraExport& camera,
                const std::vector<GBAMeshExport>& meshes,
                float orbitDist,
                const std::vector<GBASoundSampleExport>& /*soundSamples*/,
                const std::vector<GBASoundInstanceExport>& /*soundInstances*/,
                const std::vector<GBASkyFrameExport>& /*skyFrames*/,
                const GBAScriptExport& /*script*/,
                const std::vector<GBABlueprintExport>& /*blueprints*/,
                const std::vector<GBABlueprintInstanceExport>& /*bpInstances*/,
                const std::vector<GBAHudElementExport>& /*hudElements*/,
                const std::vector<GBATmSceneExport>& /*tmScenes*/,
                int /*startMode*/,
                float /*midiMasterDb*/,
                const std::vector<GBARiggedMeshExport>& /*rigs*/,
                std::string& errorMsg) {
    if (!GeneratePSPMapData(runtimeDir, sprites, camera, meshes, orbitDist, errorMsg))
        return false;

    // Build EBOOT.PBP via WSL/pspdev.
    std::string wslDir = ToWslPath(runtimeDir);
    std::string buildCmd = "cd '" + wslDir + "' && make 2>&1";
    std::string out;
    int rc = RunWslCommand(buildCmd, out);
    if (rc != 0) {
        errorMsg = "psp_mapdata.h generated, but the PSP build failed (rc=" + std::to_string(rc) + "):\n" + out
                 + "\n\nIf pspdev/WSL isn't set up yet, the header is still written — build manually with `make` in psp_runtime.";
        return false;
    }

    // Copy EBOOT.PBP to the requested output if a path was given.
    if (!outputPath.empty()) {
        std::string src = wslDir + "/EBOOT.PBP";
        std::string dst = ToWslPath(outputPath);
        std::string cp = "cp '" + src + "' '" + dst + "' 2>&1";
        std::string cpout;
        RunWslCommand(cp, cpout);   // best-effort
    }
    return true;
}

} // namespace Affinity
