// Affinity PSP runtime — single translation unit that materializes the
// exporter-generated scene data. psp_mapdata.h is regenerated by the editor's
// "Export PSP" path; a placeholder version ships so the runtime builds bare.
#include "affinity_psp.h"
#include "psp_mapdata.h"
