// Affinity PSP player collision — GENERATED by Export PSP. Do not edit.
#pragma once

#define AFN_HAS_PLAYER_COL 1
#define AFN_PLAYER_COL_RADIUS (3.5753f)
#define AFN_PLAYER_COL_BOTTOM (0.0107f)
#define AFN_PLAYER_COL_TOP (24.0452f)
