#include "nds_package.h"

#include <fstream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cstring>
#include <algorithm>
#include <filesystem>

#ifdef _WIN32
#define NOMINMAX
#include <windows.h>
#endif

namespace fs = std::filesystem;

namespace Affinity
{

// ---------------------------------------------------------------------------
// Shared helpers (same as gba_package.cpp)
// ---------------------------------------------------------------------------
static int RunDevkitBash(const std::string& cmd, std::string& output)
{
    SECURITY_ATTRIBUTES sa = {};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;

    HANDLE hReadPipe, hWritePipe;
    if (!CreatePipe(&hReadPipe, &hWritePipe, &sa, 0))
        return -1;
    SetHandleInformation(hReadPipe, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si = {};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdOutput = hWritePipe;
    si.hStdError = hWritePipe;
    si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);

    PROCESS_INFORMATION pi = {};
    std::string cmdLine = "C:\\devkitPro\\msys2\\usr\\bin\\bash.exe -lc '" + cmd + "'";

    BOOL ok = CreateProcessA(
        nullptr, (LPSTR)cmdLine.c_str(),
        nullptr, nullptr, TRUE,
        CREATE_NO_WINDOW,
        nullptr, nullptr,
        &si, &pi);

    CloseHandle(hWritePipe);

    if (!ok)
    {
        CloseHandle(hReadPipe);
        output = "Failed to launch devkitPro bash";
        return -1;
    }

    output.clear();
    char buf[512];
    DWORD bytesRead;
    while (ReadFile(hReadPipe, buf, sizeof(buf) - 1, &bytesRead, nullptr) && bytesRead > 0)
    {
        buf[bytesRead] = '\0';
        output += buf;
    }

    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD exitCode = 1;
    GetExitCodeProcess(pi.hProcess, &exitCode);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    CloseHandle(hReadPipe);

    return (int)exitCode;
}

static std::string ToMsysPath(const std::string& winPath)
{
    std::string p = winPath;
    for (auto& c : p) if (c == '\\') c = '/';
    if (p.size() >= 2 && p[1] == ':')
    {
        char drive = (char)tolower(p[0]);
        p = "/" + std::string(1, drive) + p.substr(2);
    }
    return p;
}

// ---------------------------------------------------------------------------
// Coordinate conversions (same as GBA — 16.8 fixed point)
// ---------------------------------------------------------------------------
static int EditorToFixed(float editorCoord)
{
    float px = (editorCoord + 512.0f) / 4.0f;
    return (int)(px * 256.0f);
}

static int EditorHeightToFixed(float h)
{
    return (int)((h / 4.0f) * 256.0f);
}

static unsigned short EditorAngleToBrad(float radians)
{
    float a = fmodf(radians, 6.2831853f);
    if (a < 0) a += 6.2831853f;
    return (unsigned short)(a / 6.2831853f * 65536.0f);
}

static unsigned short EditorColorToRGB15(uint32_t rgba)
{
    unsigned r = ((rgba >> 0) & 0xFF) >> 3;
    unsigned g = ((rgba >> 8) & 0xFF) >> 3;
    unsigned b = ((rgba >> 16) & 0xFF) >> 3;
    return (unsigned short)(r | (g << 5) | (b << 10));
}

// ---------------------------------------------------------------------------
// Generate mapdata.h for NDS
// ---------------------------------------------------------------------------
static bool GenerateNDSMapData(const std::string& runtimeDir,
                                const std::vector<GBASpriteExport>& sprites,
                                const std::vector<GBASpriteAssetExport>& assets,
                                const GBACameraExport& camera,
                                const std::vector<GBAMeshExport>& meshes,
                                float orbitDist)
{
    fs::path outPath = fs::path(runtimeDir) / "include" / "mapdata.h";
    std::ofstream f(outPath);
    if (!f.is_open()) return false;

    f << "// Generated by Affinity editor (NDS target)\n";
    f << "#ifndef MAPDATA_H\n";
    f << "#define MAPDATA_H\n\n";
    f << "#include <nds.h>\n\n";

    // Camera start (same 16.8 fixed-point as GBA)
    f << "// Camera start position (16.8 fixed-point)\n";
    f << "#define AFN_CAM_X     " << EditorToFixed(camera.x) << "\n";
    f << "#define AFN_CAM_Z     " << EditorToFixed(camera.z) << "\n";
    f << "#define AFN_CAM_H     " << EditorHeightToFixed(camera.height) << "\n";
    f << "#define AFN_CAM_ANGLE " << EditorAngleToBrad(camera.angle) << "\n";
    f << "#define AFN_CAM_HORIZON " << (int)camera.horizon << "\n";
    f << "#define AFN_WALK_SPEED "   << (int)(camera.walkSpeed * 37.0f / 35.0f) << "\n";
    f << "#define AFN_SPRINT_SPEED " << (int)(camera.sprintSpeed * 37.0f / 35.0f) << "\n";
    f << "#define AFN_WALK_EASE_IN "    << (int)(camera.walkEaseIn * 256.0f / 100.0f) << "\n";
    f << "#define AFN_WALK_EASE_OUT "   << (int)(camera.walkEaseOut * 256.0f / 100.0f) << "\n";
    f << "#define AFN_SPRINT_EASE_IN "  << (int)(camera.sprintEaseIn * 256.0f / 100.0f) << "\n";
    f << "#define AFN_SPRINT_EASE_OUT " << (int)(camera.sprintEaseOut * 256.0f / 100.0f) << "\n";
    if (camera.drawDistance > 0.0f)
        f << "#define AFN_DRAW_DISTANCE " << (int)(camera.drawDistance / 4.0f * 256.0f) << "\n";
    if (camera.smallTriCull > 0)
        f << "#define AFN_SMALL_TRI_CULL " << camera.smallTriCull << "\n";
    f << "\n";

    // Player index
    int playerIdx = -1;
    for (size_t i = 0; i < sprites.size(); i++)
        if (sprites[i].spriteType == 1) { playerIdx = (int)i; break; }
    f << "#define AFN_PLAYER_IDX " << playerIdx << "\n";
    f << "#define AFN_ORBIT_DIST " << (int)(orbitDist / 4.0f * 256.0f) << "\n\n";

    // Sprites
    f << "#define AFN_SPRITE_COUNT " << (int)sprites.size() << "\n\n";
    if (!sprites.empty())
    {
        f << "static const int afn_sprite_data[][10] = {\n";
        for (size_t i = 0; i < sprites.size(); i++)
        {
            int gx = EditorToFixed(sprites[i].x);
            int gy = EditorHeightToFixed(sprites[i].y);
            int gz = EditorToFixed(sprites[i].z);
            int pal = sprites[i].palIdx;
            int aIdx = sprites[i].assetIdx;
            int scaleFixed = (int)(sprites[i].scale * 256.0f);
            int sType = sprites[i].spriteType;
            int rotBrad = (int)(sprites[i].rotation * 65536.0f / 360.0f) & 0xFFFF;
            int animEn = sprites[i].animEnabled ? 1 : 0;
            int meshIdx2 = sprites[i].meshIdx;
            f << "    { " << gx << ", " << gy << ", " << gz << ", "
              << pal << ", " << aIdx << ", " << scaleFixed << ", "
              << sType << ", " << rotBrad << ", " << animEn << ", " << meshIdx2 << " },\n";
        }
        f << "};\n\n";
    }

    // ---- Mesh assets ----
    f << "#define AFN_MESH_COUNT " << (int)meshes.size() << "\n\n";

    if (!meshes.empty())
    {
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            const auto& mesh = meshes[mi];
            int vc = (int)mesh.positions.size() / 3;
            int ic = (int)mesh.indices.size();
            int qic = (int)mesh.quadIndices.size();

            // Vertex positions as s16 (8.8 fixed-point, same as GBA)
            f << "static const s16 afn_mesh" << mi << "_verts[] = {\n";
            for (int v = 0; v < vc; v++)
            {
                float px = mesh.positions[v * 3 + 0];
                float py = mesh.positions[v * 3 + 1];
                float pz = mesh.positions[v * 3 + 2];
                // Same scaling as GBA: /4 * 256 = 8.8 fixed
                int16_t fx = (int16_t)(px / 4.0f * 256.0f);
                int16_t fy = (int16_t)(py / 4.0f * 256.0f);
                int16_t fz = (int16_t)(pz / 4.0f * 256.0f);
                f << "    " << fx << ", " << fy << ", " << fz << ",\n";
            }
            f << "};\n";

            // Normals as s8 (0.7 signed fixed-point)
            f << "static const s8 afn_mesh" << mi << "_norms[] = {\n";
            for (int v = 0; v < vc; v++)
            {
                float nx = mesh.normals[v * 3 + 0];
                float ny = mesh.normals[v * 3 + 1];
                float nz = mesh.normals[v * 3 + 2];
                int8_t fnx = (int8_t)std::max(-127.0f, std::min(127.0f, nx * 127.0f));
                int8_t fny = (int8_t)std::max(-127.0f, std::min(127.0f, ny * 127.0f));
                int8_t fnz = (int8_t)std::max(-127.0f, std::min(127.0f, nz * 127.0f));
                f << "    " << (int)fnx << ", " << (int)fny << ", " << (int)fnz << ",\n";
            }
            f << "};\n";

            // Triangle indices
            f << "static const u16 afn_mesh" << mi << "_idx[] = {\n    ";
            for (int i = 0; i < ic; i++)
            {
                f << mesh.indices[i];
                if (i + 1 < ic) f << ", ";
                if ((i + 1) % 12 == 0) f << "\n    ";
            }
            if (ic == 0) f << "0"; // placeholder
            f << "\n};\n";

            // Quad indices
            f << "static const u16 afn_mesh" << mi << "_qidx[] = {\n    ";
            for (int i = 0; i < qic; i++)
            {
                f << mesh.quadIndices[i];
                if (i + 1 < qic) f << ", ";
                if ((i + 1) % 12 == 0) f << "\n    ";
            }
            if (qic == 0) f << "0";
            f << "\n};\n";

            // Texture data (if textured)
            if (mesh.textured && mesh.texW > 0 && mesh.texH > 0 && !mesh.texPixels.empty())
            {
                f << "static const u8 afn_mesh" << mi << "_tex[] = {\n    ";
                int texSize = mesh.texW * mesh.texH;
                for (int i = 0; i < texSize && i < (int)mesh.texPixels.size(); i++)
                {
                    f << (int)mesh.texPixels[i];
                    if (i + 1 < texSize) f << ", ";
                    if ((i + 1) % 16 == 0) f << "\n    ";
                }
                f << "\n};\n";

                // Texture palette (RGB15)
                f << "static const u16 afn_mesh" << mi << "_texpal[] = { ";
                for (int i = 0; i < 16; i++)
                {
                    char hex[8];
                    snprintf(hex, sizeof(hex), "0x%04X", mesh.texPalette[i]);
                    f << hex;
                    if (i < 15) f << ", ";
                }
                f << " };\n";
            }

            f << "\n";
        }

        // Pointer arrays
        f << "static const s16* afn_mesh_vert_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_verts";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const s8* afn_mesh_norm_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_norms";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const u16* afn_mesh_idx_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_idx";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const u16* afn_mesh_qidx_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_qidx";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        // Texture data pointers
        f << "static const u8* afn_mesh_tex_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            if (meshes[mi].textured && meshes[mi].texW > 0)
                f << "afn_mesh" << mi << "_tex";
            else
                f << "(const u8*)0";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const u16* afn_mesh_tex_pal_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            if (meshes[mi].textured && meshes[mi].texW > 0)
                f << "afn_mesh" << mi << "_texpal";
            else
                f << "(const u16*)0";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        // Mesh descriptor: { vertCount, indexCount, quadIdxCount, colorRGB15, cullMode, lit, sorted, halfRes, textured, texW, texShift, texPalBase, wireframe, grayscale }
        f << "static const int afn_mesh_desc[][14] = {\n";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            const auto& mesh = meshes[mi];
            int vc = (int)mesh.positions.size() / 3;
            int ic = (int)mesh.indices.size();
            int qic = (int)mesh.quadIndices.size();

            // Compute texShift for power-of-2 textures
            int texShift = 0;
            int tw = mesh.texW;
            while (tw > 1) { tw >>= 1; texShift++; }

            f << "    { " << vc << ", " << ic << ", " << qic << ", "
              << mesh.colorRGB15 << ", " << mesh.cullMode << ", "
              << mesh.lit << ", 0, " << mesh.halfRes << ", "
              << mesh.textured << ", " << mesh.texW << ", "
              << texShift << ", 0, "
              << mesh.wireframe << ", " << mesh.grayscale << " },\n";
        }
        f << "};\n\n";
    }

    f << "#endif // MAPDATA_H\n";
    f.close();
    return true;
}

// ---------------------------------------------------------------------------
// PackageNDS entry point
// ---------------------------------------------------------------------------
bool PackageNDS(const std::string& runtimeDir,
                const std::string& outputPath,
                const std::vector<GBASpriteExport>& sprites,
                const std::vector<GBASpriteAssetExport>& assets,
                const GBACameraExport& camera,
                const std::vector<GBAMeshExport>& meshes,
                float orbitDist,
                std::string& errorMsg)
{
    std::string buildOutput;
    std::string msysDir = ToMsysPath(runtimeDir);

    // Step 0: Generate mapdata.h
    if (!GenerateNDSMapData(runtimeDir, sprites, assets, camera, meshes, orbitDist))
    {
        errorMsg = "Failed to write mapdata.h to " + runtimeDir + "/include/";
        return false;
    }

    // Step 1: Clean
    {
        std::string out;
        std::string cmd = "cd '" + msysDir + "' && make clean 2>&1";
        RunDevkitBash(cmd, out);
        buildOutput += out;
    }

    // Step 2: Build
    {
        std::string out;
        std::string cmd = "cd '" + msysDir + "' && make 2>&1";
        int rc = RunDevkitBash(cmd, out);
        buildOutput += out;

        if (rc != 0)
        {
            errorMsg = "NDS build failed (exit code " + std::to_string(rc) + "):\n\n" + buildOutput;
            return false;
        }
    }

    // Step 3: Verify .nds exists
    fs::path ndsPath = fs::path(runtimeDir) / "affinity.nds";
    if (!fs::exists(ndsPath))
    {
        errorMsg = "Build succeeded but affinity.nds not found.\n\n" + buildOutput;
        return false;
    }

    // Copy to output path if different
    if (fs::path(outputPath) != ndsPath)
    {
        std::error_code ec;
        fs::copy_file(ndsPath, outputPath, fs::copy_options::overwrite_existing, ec);
        if (ec)
        {
            errorMsg = "Build succeeded but failed to copy .nds: " + ec.message() + "\n\n" + buildOutput;
            return false;
        }
    }

    errorMsg = buildOutput;
    return true;
}

} // namespace Affinity
