#include "nds_package.h"

#include <fstream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cstring>
#include <algorithm>
#include <filesystem>
#include <map>
#include <vector>
#include <array>

#ifdef _WIN32
#define NOMINMAX
#include <windows.h>
#endif

namespace fs = std::filesystem;

namespace Affinity
{

// ---------------------------------------------------------------------------
// Shared helpers (same as gba_package.cpp)
// ---------------------------------------------------------------------------
static int RunDevkitBash(const std::string& cmd, std::string& output)
{
    SECURITY_ATTRIBUTES sa = {};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;

    HANDLE hReadPipe, hWritePipe;
    if (!CreatePipe(&hReadPipe, &hWritePipe, &sa, 0))
        return -1;
    SetHandleInformation(hReadPipe, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si = {};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;
    si.hStdOutput = hWritePipe;
    si.hStdError = hWritePipe;
    si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);

    PROCESS_INFORMATION pi = {};
    std::string cmdLine = "C:\\devkitPro\\msys2\\usr\\bin\\bash.exe -lc '" + cmd + "'";

    BOOL ok = CreateProcessA(
        nullptr, (LPSTR)cmdLine.c_str(),
        nullptr, nullptr, TRUE,
        CREATE_NO_WINDOW,
        nullptr, nullptr,
        &si, &pi);

    CloseHandle(hWritePipe);

    if (!ok)
    {
        CloseHandle(hReadPipe);
        output = "Failed to launch devkitPro bash";
        return -1;
    }

    output.clear();
    char buf[512];
    DWORD bytesRead;
    while (ReadFile(hReadPipe, buf, sizeof(buf) - 1, &bytesRead, nullptr) && bytesRead > 0)
    {
        buf[bytesRead] = '\0';
        output += buf;
    }

    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD exitCode = 1;
    GetExitCodeProcess(pi.hProcess, &exitCode);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    CloseHandle(hReadPipe);

    return (int)exitCode;
}

static std::string ToMsysPath(const std::string& winPath)
{
    std::string p = winPath;
    for (auto& c : p) if (c == '\\') c = '/';
    if (p.size() >= 2 && p[1] == ':')
    {
        char drive = (char)tolower(p[0]);
        p = "/" + std::string(1, drive) + p.substr(2);
    }
    return p;
}

// ---------------------------------------------------------------------------
// Coordinate conversions (same as GBA — 16.8 fixed point)
// ---------------------------------------------------------------------------
static int EditorToFixed(float editorCoord)
{
    float px = (editorCoord + 512.0f) / 4.0f;
    return (int)(px * 256.0f);
}

static int EditorHeightToFixed(float h)
{
    return (int)((h / 4.0f) * 256.0f);
}

static unsigned short EditorAngleToBrad(float radians)
{
    float a = fmodf(radians, 6.2831853f);
    if (a < 0) a += 6.2831853f;
    return (unsigned short)(a / 6.2831853f * 65536.0f);
}

static unsigned short EditorColorToRGB15(uint32_t rgba)
{
    unsigned r = ((rgba >> 0) & 0xFF) >> 3;
    unsigned g = ((rgba >> 8) & 0xFF) >> 3;
    unsigned b = ((rgba >> 16) & 0xFF) >> 3;
    return (unsigned short)(r | (g << 5) | (b << 10));
}

// ---------------------------------------------------------------------------
// Generate mapdata.h for NDS
// ---------------------------------------------------------------------------
static bool GenerateNDSMapData(const std::string& runtimeDir,
                                const std::vector<GBASpriteExport>& sprites,
                                const std::vector<GBASpriteAssetExport>& assets,
                                const GBACameraExport& camera,
                                const std::vector<GBAMeshExport>& meshes,
                                float orbitDist,
                                const std::vector<GBASoundSampleExport>& soundSamples,
                                const std::vector<GBASoundInstanceExport>& soundInstances,
                                const std::vector<GBASkyFrameExport>& skyFrames,
                                bool ndsAntialiasing)
{
    fs::path outPath = fs::path(runtimeDir) / "include" / "mapdata.h";
    std::ofstream f(outPath);
    if (!f.is_open()) return false;

    f << "// Generated by Affinity editor (NDS target)\n";
    f << "#ifndef MAPDATA_H\n";
    f << "#define MAPDATA_H\n\n";
    f << "#include <nds.h>\n\n";
    if (ndsAntialiasing) f << "#define AFN_NDS_AA 1\n\n";

    // Camera start (same 16.8 fixed-point as GBA)
    f << "// Camera start position (16.8 fixed-point)\n";
    f << "#define AFN_CAM_X     " << EditorToFixed(camera.x) << "\n";
    f << "#define AFN_CAM_Z     " << EditorToFixed(camera.z) << "\n";
    f << "#define AFN_CAM_H     " << EditorHeightToFixed(camera.height) << "\n";
    f << "#define AFN_CAM_ANGLE " << EditorAngleToBrad(camera.angle) << "\n";
    f << "#define AFN_CAM_HORIZON " << (int)camera.horizon << "\n";
    f << "#define AFN_WALK_SPEED "   << (int)(camera.walkSpeed * 37.0f / 35.0f) << "\n";
    f << "#define AFN_SPRINT_SPEED " << (int)(camera.sprintSpeed * 37.0f / 35.0f) << "\n";
    f << "#define AFN_WALK_EASE_IN "    << (int)(camera.walkEaseIn * 256.0f / 100.0f) << "\n";
    f << "#define AFN_WALK_EASE_OUT "   << (int)(camera.walkEaseOut * 256.0f / 100.0f) << "\n";
    f << "#define AFN_SPRINT_EASE_IN "  << (int)(camera.sprintEaseIn * 256.0f / 100.0f) << "\n";
    f << "#define AFN_SPRINT_EASE_OUT " << (int)(camera.sprintEaseOut * 256.0f / 100.0f) << "\n";
    if (camera.drawDistance > 0.0f)
        f << "#define AFN_DRAW_DISTANCE " << (int)(camera.drawDistance / 4.0f * 256.0f) << "\n";
    if (camera.spriteDrawDistance > 0.0f)
        f << "#define AFN_SPRITE_DRAW_DISTANCE " << (int)(camera.spriteDrawDistance / 4.0f * 256.0f) << "\n";
    if (camera.smallTriCull > 0)
        f << "#define AFN_SMALL_TRI_CULL " << camera.smallTriCull << "\n";
    f << "\n";

    // Player index
    int playerIdx = -1;
    for (size_t i = 0; i < sprites.size(); i++)
        if (sprites[i].spriteType == 1) { playerIdx = (int)i; break; }
    f << "#define AFN_PLAYER_IDX " << playerIdx << "\n";
    f << "#define AFN_ORBIT_DIST " << (int)(orbitDist / 4.0f * 256.0f) << "\n\n";

    // Sprites
    f << "#define AFN_SPRITE_COUNT " << (int)sprites.size() << "\n\n";
    if (!sprites.empty())
    {
        // Sprite row: x, y, z, pal, asset, scale, type, rot, animEn, meshIdx, forceStatic
        f << "static const int afn_sprite_data[][11] = {\n";
        for (size_t i = 0; i < sprites.size(); i++)
        {
            int gx = EditorToFixed(sprites[i].x);
            int gy = EditorHeightToFixed(sprites[i].y);
            int gz = EditorToFixed(sprites[i].z);
            int pal = sprites[i].palIdx;
            int aIdx = sprites[i].assetIdx;
            int scaleFixed = (int)(sprites[i].scale * 256.0f);
            int sType = sprites[i].spriteType;
            int rotBrad = (int)(sprites[i].rotation * 65536.0f / 360.0f) & 0xFFFF;
            int animEn = sprites[i].animEnabled ? 1 : 0;
            int meshIdx2 = sprites[i].meshIdx;
            int fStatic = sprites[i].forceStatic ? 1 : 0;
            f << "    { " << gx << ", " << gy << ", " << gz << ", "
              << pal << ", " << aIdx << ", " << scaleFixed << ", "
              << sType << ", " << rotBrad << ", " << animEn << ", "
              << meshIdx2 << ", " << fStatic << " },\n";
        }
        f << "};\n\n";
    }

    // ---- Sprite assets (OAM tiles + palette + descriptor) ----
    // Simplified vs GBA: skip directional animation streaming and tile-reference
    // optimization. Every asset's frames get tiles in afn_all_tiles, every asset
    // gets one palette in afn_pal[][16]. NDS OBJ VRAM is 128KB (4× GBA) so we
    // can afford the wasteful layout for a first cut.
    f << "#define AFN_ASSET_COUNT " << (int)assets.size() << "\n\n";
    if (!assets.empty()) {
        // Pack each asset's frames into 8x8 4bpp tiles. Per-frame: tiles laid
        // out in row-major tile order (left-to-right tile columns, top-to-bottom
        // tile rows) so OBJ_1D mapping reads consecutive tiles for one sprite.
        std::vector<uint32_t> allTiles;
        std::vector<int> assetTileStart(assets.size(), 0);
        std::vector<int> assetTilesPerFrame(assets.size(), 0);
        std::vector<int> assetObjSize(assets.size(), 0);
        std::vector<int> assetDirCount(assets.size(), 1);  // 1 = static, 8 = directional
        // Per-asset derived palette in RGB15. For directional assets the
        // editor's a.palette[] is empty (real colors live in dirImages RGBA);
        // we build a 15-color palette by counting unique RGB15 pixels and
        // merging nearest pairs until ≤15 remain — mirrors gba_package.cpp:584.
        std::vector<std::array<uint16_t, 16>> assetPal(assets.size());
        for (auto& p : assetPal) p.fill(0);

        // Which assets need static emission only (some sprite using them has
        // forceStatic=true). Mirrors gba_package.cpp:368-373.
        std::vector<bool> assetForceStatic(assets.size(), false);
        for (const auto& s : sprites)
            if (s.forceStatic && s.assetIdx >= 0 && s.assetIdx < (int)assets.size())
                assetForceStatic[s.assetIdx] = true;
        for (size_t ai = 0; ai < assets.size(); ai++) {
            assetTileStart[ai] = (int)allTiles.size() / 8;
            const auto& a = assets[ai];
            int sz = a.baseSize > 0 ? a.baseSize : 16;
            // If a directional asset's dirImage is bigger than baseSize, the
            // baseSize is just the runtime-streamed slot — the source image
            // is the real OBJ size. Round up to OBJ-allowed sizes {8,16,32,64}
            // so the OAM sprite covers the whole picture, not just the corner.
            if (a.hasDirections && !a.dirAnimSets.empty()
                && a.dirAnimSets[0].dirImages[0].pixels) {
                int dw = a.dirAnimSets[0].dirImages[0].width;
                int dh = a.dirAnimSets[0].dirImages[0].height;
                int big = dw > dh ? dw : dh;
                int objSz =  big <= 8  ? 8  :
                             big <= 16 ? 16 :
                             big <= 32 ? 32 : 64;
                if (objSz > sz) sz = objSz;
            }
            assetObjSize[ai] = sz;
            int tilesPerSide = sz / 8;
            int tilesPerFrame = tilesPerSide * tilesPerSide;
            assetTilesPerFrame[ai] = tilesPerFrame;
            // Pick a source for the tile data: prefer a.frames; if empty and
            // the asset has directions (player character etc.), fall back to
            // direction 0 of dirAnimSets[0] (RGBA → nearest-palette quantized).
            auto emitFrame = [&](const uint8_t* pixels, int fw, int fh, bool stride64) {
                int stride = stride64 ? kExportMaxFrameSize : fw;
                for (int ty = 0; ty < tilesPerSide; ty++)
                for (int tx = 0; tx < tilesPerSide; tx++) {
                    for (int py = 0; py < 8; py++) {
                        uint32_t word = 0;
                        for (int px = 0; px < 8; px++) {
                            int sx = tx * 8 + px;
                            int sy = ty * 8 + py;
                            uint8_t pix = (sx < fw && sy < fh) ? pixels[sy * stride + sx] : 0;
                            word |= ((uint32_t)(pix & 0xF)) << (px * 4);
                        }
                        allTiles.push_back(word);
                    }
                }
            };

            // Prefer directional data when present — frames[] may be a zero
            // placeholder for directional assets (the real pixels live in
            // dirAnimSets and get DMA-streamed at runtime on GBA).
            bool usedDir = false;
            if (a.hasDirections && !a.dirAnimSets.empty()
                && a.dirAnimSets[0].dirImages[0].pixels) {

                // Build palette from ALL non-empty dirImages (palette must
                // cover every direction's colors, not just direction 0).
                struct CF { uint16_t c; int n; };
                std::vector<CF> freqs;
                auto addColor = [&](uint16_t c) {
                    for (auto& f : freqs) if (f.c == c) { f.n++; return; }
                    freqs.push_back({c, 1});
                };
                for (int d = 0; d < 8; d++) {
                    const auto& img = a.dirAnimSets[0].dirImages[d];
                    if (!img.pixels || img.width <= 0 || img.height <= 0) continue;
                    for (int yy = 0; yy < img.height; yy++)
                    for (int xx = 0; xx < img.width; xx++) {
                        const uint8_t* p = img.pixels + (yy * img.width + xx) * 4;
                        if (p[3] < 128) continue;
                        uint16_t c15 = (p[0] >> 3) | ((p[1] >> 3) << 5) | ((p[2] >> 3) << 10);
                        addColor(c15);
                    }
                }
                while ((int)freqs.size() > 15) {
                    int bI = 0, bJ = 1, bD = 1 << 30;
                    for (size_t i = 0; i < freqs.size(); i++)
                    for (size_t j = i + 1; j < freqs.size(); j++) {
                        int dr = (int)(freqs[i].c & 31) - (int)(freqs[j].c & 31);
                        int dg = (int)((freqs[i].c >> 5) & 31) - (int)((freqs[j].c >> 5) & 31);
                        int db = (int)((freqs[i].c >> 10) & 31) - (int)((freqs[j].c >> 10) & 31);
                        int d = dr*dr + dg*dg + db*db;
                        if (d < bD) { bD = d; bI = (int)i; bJ = (int)j; }
                    }
                    if (freqs[bI].n < freqs[bJ].n) freqs[bI].c = freqs[bJ].c;
                    freqs[bI].n += freqs[bJ].n;
                    freqs.erase(freqs.begin() + bJ);
                }
                assetPal[ai][0] = 0;
                for (size_t i = 0; i < freqs.size() && i < 15; i++)
                    assetPal[ai][i + 1] = freqs[i].c;

                // Quantize + emit every direction. ForceStatic assets only
                // need direction 0 (1 frame). All others get all 8 dirs.
                int dirCount = assetForceStatic[ai] ? 1 : 8;
                assetDirCount[ai] = dirCount;
                for (int d = 0; d < dirCount; d++) {
                    const auto& img = a.dirAnimSets[0].dirImages[d];
                    int fw = (img.pixels ? img.width  : 0);
                    int fh = (img.pixels ? img.height : 0);
                    // Empty direction (e.g. only N/S/E/W populated) → fall
                    // back to direction 0 so the slot still has data.
                    const auto* src = img.pixels ? &img : &a.dirAnimSets[0].dirImages[0];
                    fw = src->width;
                    fh = src->height;
                    std::vector<uint8_t> palIdx(fw * fh, 0);
                    for (int yy = 0; yy < fh; yy++)
                    for (int xx = 0; xx < fw; xx++) {
                        const uint8_t* p = src->pixels + (yy * fw + xx) * 4;
                        if (p[3] < 128) { palIdx[yy*fw+xx] = 0; continue; }
                        int r5 = p[0] >> 3, g5 = p[1] >> 3, b5 = p[2] >> 3;
                        int best = 1, bestD = 1 << 30;
                        for (size_t i = 0; i < freqs.size(); i++) {
                            int pr = freqs[i].c & 31;
                            int pg = (freqs[i].c >> 5) & 31;
                            int pb = (freqs[i].c >> 10) & 31;
                            int dd = (r5-pr)*(r5-pr) + (g5-pg)*(g5-pg) + (b5-pb)*(b5-pb);
                            if (dd < bestD) { bestD = dd; best = (int)i + 1; }
                        }
                        palIdx[yy*fw+xx] = (uint8_t)best;
                    }
                    emitFrame(palIdx.data(), fw, fh, false);
                }
                usedDir = true;
            }
            if (!usedDir) {
                for (int c = 0; c < 16; c++)
                    assetPal[ai][c] = EditorColorToRGB15(a.palette[c]);
                for (auto& fr : a.frames)
                    emitFrame(fr.pixels, fr.width > 0 ? fr.width : sz,
                              fr.height > 0 ? fr.height : sz, true);
            }
        }
        f << "static const u32 afn_all_tiles[" << (allTiles.empty() ? 1 : (int)allTiles.size()) << "] = {";
        if (allTiles.empty()) f << " 0 ";
        else {
            for (size_t i = 0; i < allTiles.size(); i++) {
                if (i % 8 == 0) f << "\n    ";
                char hex[12]; snprintf(hex, sizeof(hex), "0x%08X", allTiles[i]);
                f << hex;
                if (i + 1 < allTiles.size()) f << ",";
            }
            f << "\n";
        }
        f << "};\n";
        f << "#define AFN_ALL_TILES_LEN " << (int)allTiles.size() * 4 << "\n\n";

        // Per-asset RGB15 palette (16 entries, index 0 = transparent).
        // assetPal was built per-asset during tile emission — directional
        // assets get a histogram-derived palette, non-directional reuse
        // the editor's a.palette[].
        f << "static const u16 afn_pal[" << assets.size() << "][16] = {\n";
        for (size_t ai = 0; ai < assets.size(); ai++) {
            f << "    { ";
            for (int c = 0; c < 16; c++) {
                char hex[8]; snprintf(hex, sizeof(hex), "0x%04X", assetPal[ai][c]);
                f << hex;
                if (c < 15) f << ", ";
            }
            f << " },\n";
        }
        f << "};\n";

        // Per-asset descriptor: {tileStart, tilesPerFrame, frameCount, objSize, palBank, dirCount}
        // NDS has 16 OBJ palette banks — assign each asset a unique bank (0..15)
        // so palettes don't overwrite each other on upload. dirCount = 8 for
        // directional assets (Sonic, etc), 1 for static — runtime indexes into
        // tile data as tileStart + dir * tilesPerFrame.
        f << "static const int afn_asset_desc[][6] = {\n";
        for (size_t ai = 0; ai < assets.size(); ai++) {
            int palBank = (int)ai & 0xF;
            f << "    { " << assetTileStart[ai] << ", " << assetTilesPerFrame[ai] << ", "
              << (int)assets[ai].frames.size() << ", " << assetObjSize[ai] << ", "
              << palBank << ", " << assetDirCount[ai] << " },\n";
        }
        f << "};\n\n";
    }

    // ---- Mesh assets ----
    f << "#define AFN_MESH_COUNT " << (int)meshes.size() << "\n\n";

    if (!meshes.empty())
    {
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            const auto& mesh = meshes[mi];
            int vc = (int)mesh.positions.size() / 3;
            int ic = (int)mesh.indices.size();
            int qic = (int)mesh.quadIndices.size();

            // Vertex positions as s16 (8.8 fixed-point, same as GBA)
            f << "static const s16 afn_mesh" << mi << "_verts[] = {\n";
            for (int v = 0; v < vc; v++)
            {
                float px = mesh.positions[v * 3 + 0];
                float py = mesh.positions[v * 3 + 1];
                float pz = mesh.positions[v * 3 + 2];
                // Same scaling as GBA: /4 * 256 = 8.8 fixed
                int16_t fx = (int16_t)(px / 4.0f * 256.0f);
                int16_t fy = (int16_t)(py / 4.0f * 256.0f);
                int16_t fz = (int16_t)(pz / 4.0f * 256.0f);
                f << "    " << fx << ", " << fy << ", " << fz << ",\n";
            }
            f << "};\n";

            // Normals as s8 (0.7 signed fixed-point)
            f << "static const s8 afn_mesh" << mi << "_norms[] = {\n";
            for (int v = 0; v < vc; v++)
            {
                float nx = mesh.normals[v * 3 + 0];
                float ny = mesh.normals[v * 3 + 1];
                float nz = mesh.normals[v * 3 + 2];
                int8_t fnx = (int8_t)std::max(-127.0f, std::min(127.0f, nx * 127.0f));
                int8_t fny = (int8_t)std::max(-127.0f, std::min(127.0f, ny * 127.0f));
                int8_t fnz = (int8_t)std::max(-127.0f, std::min(127.0f, nz * 127.0f));
                f << "    " << (int)fnx << ", " << (int)fny << ", " << (int)fnz << ",\n";
            }
            f << "};\n";

            // Texture coordinates as t16 (4.12 fixed = u * texW * 16, v * texH * 16).
            // Only meaningful when textured; emit zeros otherwise so the runtime
            // can unconditionally read afn_meshN_uvs without an extra null check.
            f << "static const s16 afn_mesh" << mi << "_uvs[] = {\n";
            for (int v = 0; v < vc; v++)
            {
                float u = (v * 2 + 0 < (int)mesh.uvs.size()) ? mesh.uvs[v * 2 + 0] : 0.0f;
                float vv = (v * 2 + 1 < (int)mesh.uvs.size()) ? mesh.uvs[v * 2 + 1] : 0.0f;
                int16_t tu = (int16_t)(u * mesh.texW * 16.0f);
                int16_t tv = (int16_t)(vv * mesh.texH * 16.0f);
                f << "    " << tu << ", " << tv << ",\n";
            }
            f << "};\n";

            // Triangle indices
            f << "static const u16 afn_mesh" << mi << "_idx[] = {\n    ";
            for (int i = 0; i < ic; i++)
            {
                f << mesh.indices[i];
                if (i + 1 < ic) f << ", ";
                if ((i + 1) % 12 == 0) f << "\n    ";
            }
            if (ic == 0) f << "0"; // placeholder
            f << "\n};\n";

            // Quad indices
            f << "static const u16 afn_mesh" << mi << "_qidx[] = {\n    ";
            for (int i = 0; i < qic; i++)
            {
                f << mesh.quadIndices[i];
                if (i + 1 < qic) f << ", ";
                if ((i + 1) % 12 == 0) f << "\n    ";
            }
            if (qic == 0) f << "0";
            f << "\n};\n";

            // Texture data (if textured). NDS GL_RGB16 (4bpp paletted) packs
            // 2 pixels per byte (low nibble = even pixel, high nibble = odd).
            // GBA texture pixels in the source vector are 1 per byte, so we
            // pair them up here.
            if (mesh.textured && mesh.texW > 0 && mesh.texH > 0 && !mesh.texPixels.empty())
            {
                f << "static const u8 afn_mesh" << mi << "_tex[] = {\n    ";
                int texPx = mesh.texW * mesh.texH;
                int packed = (texPx + 1) / 2;
                for (int i = 0; i < packed; i++)
                {
                    int lo = (i * 2 + 0 < (int)mesh.texPixels.size()) ? (mesh.texPixels[i*2+0] & 0xF) : 0;
                    int hi = (i * 2 + 1 < (int)mesh.texPixels.size()) ? (mesh.texPixels[i*2+1] & 0xF) : 0;
                    f << ((hi << 4) | lo);
                    if (i + 1 < packed) f << ", ";
                    if ((i + 1) % 16 == 0) f << "\n    ";
                }
                f << "\n};\n";

                // Texture palette (RGB15)
                f << "static const u16 afn_mesh" << mi << "_texpal[] = { ";
                for (int i = 0; i < 16; i++)
                {
                    char hex[8];
                    snprintf(hex, sizeof(hex), "0x%04X", mesh.texPalette[i]);
                    f << hex;
                    if (i < 15) f << ", ";
                }
                f << " };\n";
            }

            f << "\n";
        }

        // Pointer arrays
        f << "static const s16* afn_mesh_vert_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_verts";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const s8* afn_mesh_norm_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_norms";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const u16* afn_mesh_idx_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_idx";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const u16* afn_mesh_qidx_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_qidx";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const s16* afn_mesh_uv_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            f << "afn_mesh" << mi << "_uvs";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        // Texture data pointers
        f << "static const u8* afn_mesh_tex_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            if (meshes[mi].textured && meshes[mi].texW > 0)
                f << "afn_mesh" << mi << "_tex";
            else
                f << "(const u8*)0";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        f << "static const u16* afn_mesh_tex_pal_ptrs[] = { ";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            if (meshes[mi].textured && meshes[mi].texW > 0)
                f << "afn_mesh" << mi << "_texpal";
            else
                f << "(const u16*)0";
            if (mi + 1 < meshes.size()) f << ", ";
        }
        f << " };\n";

        // Mesh descriptor: { vertCount, indexCount, quadIdxCount, colorRGB15, cullMode, lit, sorted, halfRes, textured, texW, texShift, texPalBase, wireframe, grayscale, drawDist, visible }
        f << "static const int afn_mesh_desc[][16] = {\n";
        for (size_t mi = 0; mi < meshes.size(); mi++)
        {
            const auto& mesh = meshes[mi];
            int vc = (int)mesh.positions.size() / 3;
            int ic = (int)mesh.indices.size();
            int qic = (int)mesh.quadIndices.size();

            // Compute texShift for power-of-2 textures
            int texShift = 0;
            int tw = mesh.texW;
            while (tw > 1) { tw >>= 1; texShift++; }

            int drawDist = 0;
            if (mesh.drawDistance > 0.0f)
                drawDist = (int)(mesh.drawDistance / 4.0f * 256.0f);

            f << "    { " << vc << ", " << ic << ", " << qic << ", "
              << mesh.colorRGB15 << ", " << mesh.cullMode << ", "
              << mesh.lit << ", 0, " << mesh.halfRes << ", "
              << mesh.textured << ", " << mesh.texW << ", "
              << texShift << ", 0, "
              << mesh.wireframe << ", " << mesh.grayscale << ", " << drawDist << ", "
              << mesh.visible << " },\n";
        }
        f << "};\n\n";
    }

    // ---- Sound / PCM Audio Data (NDS path — hardware mixer on ARM7) ----
    // GBA-only mixer toggles (compat/hifi/lowrate/bufscale/mixpad/premix/
    // isrswap/chunked/attenuate_a/triplebuf) are NOT emitted — there is no
    // ARM9 software mixer to tune.
    if (!soundSamples.empty()) {
        f << "\n// ---- PCM Samples ----\n";
        f << "#define AFN_SOUND_SAMPLE_COUNT " << soundSamples.size() << "\n";
        f << "#define AFN_SOUND_INSTANCE_COUNT " << soundInstances.size() << "\n\n";

        for (int i = 0; i < (int)soundSamples.size(); i++) {
            auto& smp = soundSamples[i];
            bool use16 = !smp.data16.empty() && (int)smp.data16.size() == (int)smp.data.size();
            if (use16) {
                f << "static const s16 afn_pcm_" << i << "[] __attribute__((aligned(4))) = {\n    ";
                for (int j = 0; j < (int)smp.data16.size(); j++) {
                    f << (int)smp.data16[j] << ",";
                    if ((j & 15) == 15) f << "\n    ";
                }
                int padVal = 0;
                if (smp.loop && smp.loopStart >= 0 && smp.loopStart < (int)smp.data16.size())
                    padVal = (int)smp.data16[smp.loopStart];
                f << padVal << "\n};\n";
            } else {
                f << "static const s8 afn_pcm_" << i << "[] __attribute__((aligned(4))) = {\n    ";
                for (int j = 0; j < (int)smp.data.size(); j++) {
                    f << (int)smp.data[j] << ",";
                    if ((j & 31) == 31) f << "\n    ";
                }
                int padVal = 0;
                if (smp.loop && smp.loopStart >= 0 && smp.loopStart < (int)smp.data.size())
                    padVal = (int)smp.data[smp.loopStart];
                f << padVal << "\n};\n";
            }
            f << "#define AFN_PCM_" << i << "_LEN " << smp.data.size() << "\n";
            f << "#define AFN_PCM_" << i << "_RATE " << smp.sampleRate << "\n";
            f << "#define AFN_PCM_" << i << "_16BIT " << (use16 ? 1 : 0) << "\n\n";
        }

        f << "static const void* const afn_pcm_ptrs[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++)
            f << "    afn_pcm_" << i << ",\n";
        f << "};\n";
        f << "static const u8 afn_pcm_is16[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++) {
            bool use16 = !soundSamples[i].data16.empty() && (int)soundSamples[i].data16.size() == (int)soundSamples[i].data.size();
            f << "    " << (use16 ? 1 : 0) << ",\n";
        }
        f << "};\n";
        f << "static const int afn_pcm_lens[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++)
            f << "    AFN_PCM_" << i << "_LEN,\n";
        f << "};\n";
        f << "static const int afn_pcm_rates[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++)
            f << "    AFN_PCM_" << i << "_RATE,\n";
        f << "};\n";
        f << "static const u8 afn_pcm_loop[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++)
            f << "    " << (soundSamples[i].loop ? 1 : 0) << ",\n";
        f << "};\n";
        f << "static const int afn_pcm_loop_start[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++)
            f << "    " << soundSamples[i].loopStart << ",\n";
        f << "};\n";
        f << "static const int afn_pcm_loop_end[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++) {
            int le = soundSamples[i].loopEnd > 0 ? soundSamples[i].loopEnd : (int)soundSamples[i].data.size();
            f << "    " << le << ",\n";
        }
        f << "};\n";
        f << "static const u8 afn_pcm_vol_scale[" << soundSamples.size() << "] = {\n";
        for (int i = 0; i < (int)soundSamples.size(); i++)
            f << "    " << (soundSamples[i].volScale > 255 ? 255 : soundSamples[i].volScale) << ",\n";
        f << "};\n\n";

        f << "typedef struct { int tick; u8 note; u8 vel; u8 smpIdx; u8 channel; int dur; } AfnSndNote;\n\n";

        for (int i = 0; i < (int)soundInstances.size(); i++) {
            auto& inst = soundInstances[i];
            if (inst.notes.empty()) continue;
            f << "// Instance " << i << ": " << inst.name << "\n";
            f << "static const AfnSndNote afn_snd_notes_" << i << "[] = {\n";
            for (auto& n : inst.notes) {
                f << "    {" << n.tick << "," << n.note << "," << n.velocity << "," << n.sampleIdx << "," << n.channel << "," << n.duration << "},\n";
            }
            f << "};\n";
            f << "#define AFN_SND_" << i << "_NOTE_COUNT " << inst.notes.size() << "\n";
            f << "#define AFN_SND_" << i << "_TEMPO " << inst.tempo << "\n";
            f << "#define AFN_SND_" << i << "_TPB " << inst.ticksPerBeat << "\n\n";
        }

        f << "static const AfnSndNote* const afn_snd_note_ptrs[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++) {
            if (soundInstances[i].notes.empty()) f << "    0,\n";
            else                                 f << "    afn_snd_notes_" << i << ",\n";
        }
        f << "};\n";
        f << "static const int afn_snd_note_counts[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++)
            f << "    " << soundInstances[i].notes.size() << ",\n";
        f << "};\n";
        f << "static const int afn_snd_tpf[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++) {
            int tpf = soundInstances[i].tempo * soundInstances[i].ticksPerBeat * 256 / 3600;
            if (tpf < 1) tpf = 1;
            f << "    " << tpf << ",\n";
        }
        f << "};\n";
        f << "static const u8 afn_snd_voices[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++)
            f << "    " << soundInstances[i].voiceCount << ",\n";
        f << "};\n";
        f << "static const u8 afn_snd_loop[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++)
            f << "    " << (soundInstances[i].loop ? 1 : 0) << ",\n";
        f << "};\n";
        f << "static const int afn_snd_loop_start[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++)
            f << "    " << soundInstances[i].loopStartTick << ",\n";
        f << "};\n";
        f << "static const int afn_snd_loop_end[" << soundInstances.size() << "] = {\n";
        for (int i = 0; i < (int)soundInstances.size(); i++) {
            int loopEnd = soundInstances[i].loopEndTick;
            if (loopEnd <= 0 && !soundInstances[i].notes.empty())
                loopEnd = soundInstances[i].notes.back().tick + soundInstances[i].notes.back().duration;
            f << "    " << loopEnd << ",\n";
        }
        f << "};\n\n";

        f << "#define AFN_HAS_SOUND 1\n";
    }

    // ---- Sky panorama (NDS: single 256x256 8bpp paletted texture) ----
    // GBA emits this as 4-band 4bpp tiles + 4 sub-palettes for Mode 7 BG2.
    // NDS gets a flat 256-color paletted texture rendered as a wrapping
    // view-space quad behind the 3D layer.
    if (!skyFrames.empty() && skyFrames[0].pixels && skyFrames[0].w > 0 && skyFrames[0].h > 0) {
        const int SKY_W = 256, SKY_H = 256;
        // Resize source frame to 256x256 via nearest-neighbor
        std::vector<unsigned char> rgba(SKY_W * SKY_H * 4);
        int srcW = skyFrames[0].w, srcH = skyFrames[0].h;
        const unsigned char* srcPx = skyFrames[0].pixels;
        for (int y = 0; y < SKY_H; y++) {
            int sy = y * srcH / SKY_H;
            for (int x = 0; x < SKY_W; x++) {
                int sx = x * srcW / SKY_W;
                memcpy(&rgba[(y * SKY_W + x) * 4], &srcPx[(sy * srcW + sx) * 4], 4);
            }
        }
        // Median-cut 256-color quantization. The standard algorithm for
        // natural images: recursively split color boxes along their longest
        // axis at the median, until you have 256 boxes. Each palette entry
        // becomes the mean of its box's pixels. Much better than top-N
        // histogram bucketing for sky gradients (which left rogue pixels
        // because rare-but-distinct colors got their own palette slots).
        struct Px { uint8_t r, g, b; };
        std::vector<Px> pixels; pixels.reserve(SKY_W * SKY_H);
        for (int i = 0; i < SKY_W * SKY_H; i++) {
            pixels.push_back({(uint8_t)(rgba[i*4+0] >> 3),
                              (uint8_t)(rgba[i*4+1] >> 3),
                              (uint8_t)(rgba[i*4+2] >> 3)});
        }
        struct Box { int lo, hi; }; // index range into `pixels`
        std::vector<Box> boxes; boxes.push_back({0, (int)pixels.size()});
        while ((int)boxes.size() < 256) {
            // Find box with largest color-axis range.
            int bestBox = -1, bestRange = 0, bestAxis = 0;
            for (int bi = 0; bi < (int)boxes.size(); bi++) {
                int lo = boxes[bi].lo, hi = boxes[bi].hi;
                if (hi - lo <= 1) continue;
                uint8_t rMin=31, rMax=0, gMin=31, gMax=0, bMin=31, bMax=0;
                for (int j = lo; j < hi; j++) {
                    Px p = pixels[j];
                    if (p.r < rMin) rMin = p.r; if (p.r > rMax) rMax = p.r;
                    if (p.g < gMin) gMin = p.g; if (p.g > gMax) gMax = p.g;
                    if (p.b < bMin) bMin = p.b; if (p.b > bMax) bMax = p.b;
                }
                int rR = rMax - rMin, gR = gMax - gMin, bR = bMax - bMin;
                int axis = 0, range = rR;
                if (gR > range) { range = gR; axis = 1; }
                if (bR > range) { range = bR; axis = 2; }
                if (range > bestRange) { bestRange = range; bestBox = bi; bestAxis = axis; }
            }
            if (bestBox < 0) break; // all boxes single-pixel
            // Sort the box along the chosen axis and split at the median.
            Box b = boxes[bestBox];
            std::sort(pixels.begin() + b.lo, pixels.begin() + b.hi,
                      [bestAxis](const Px& a, const Px& c) {
                          uint8_t av = bestAxis == 0 ? a.r : bestAxis == 1 ? a.g : a.b;
                          uint8_t cv = bestAxis == 0 ? c.r : bestAxis == 1 ? c.g : c.b;
                          return av < cv;
                      });
            int mid = b.lo + (b.hi - b.lo) / 2;
            boxes[bestBox].hi = mid;
            boxes.push_back({mid, b.hi});
        }
        std::vector<uint16_t> palette(256, 0);
        for (int i = 0; i < (int)boxes.size(); i++) {
            int lo = boxes[i].lo, hi = boxes[i].hi;
            if (hi <= lo) continue;
            uint64_t rs=0, gs=0, bs=0;
            for (int j = lo; j < hi; j++) { rs += pixels[j].r; gs += pixels[j].g; bs += pixels[j].b; }
            int n = hi - lo;
            unsigned r5 = (unsigned)((rs + n/2) / n);
            unsigned g5 = (unsigned)((gs + n/2) / n);
            unsigned b5 = (unsigned)((bs + n/2) / n);
            if (r5 > 31) r5 = 31;
            if (g5 > 31) g5 = 31;
            if (b5 > 31) b5 = 31;
            palette[i] = (uint16_t)(r5 | (g5 << 5) | (b5 << 10));
        }
        int palN = (int)boxes.size();
        // Build mapping table: each unique input color → palette index of
        // Map each unique input color → nearest palette index. Build the
        // unique-color set fresh (the histogram from before median-cut was
        // dropped); a map keyed on RGB15 dedup pixels.
        std::map<uint16_t, uint8_t> nearest;
        auto dist2 = [](uint16_t a, uint16_t b) {
            int ar=a&31, ag=(a>>5)&31, ab=(a>>10)&31;
            int br=b&31, bg=(b>>5)&31, bb=(b>>10)&31;
            return (ar-br)*(ar-br) + (ag-bg)*(ag-bg) + (ab-bb)*(ab-bb);
        };
        for (int i = 0; i < SKY_W * SKY_H; i++) {
            unsigned r = rgba[i*4+0] >> 3, g = rgba[i*4+1] >> 3, b = rgba[i*4+2] >> 3;
            uint16_t c15 = (uint16_t)(r | (g << 5) | (b << 10));
            if (nearest.count(c15)) continue;
            int best = 0, bestD = 1<<30;
            for (int p = 0; p < palN; p++) {
                int d = dist2(c15, palette[p]);
                if (d < bestD) { bestD = d; best = p; }
            }
            nearest[c15] = (uint8_t)best;
        }

        f << "\n// ---- Sky panorama (256x256 8bpp paletted) ----\n";
        f << "#define AFN_HAS_SKY 1\n";
        f << "static const u16 afn_sky_pal[256] = {\n    ";
        for (int i = 0; i < 256; i++) {
            char hex[8]; snprintf(hex, sizeof(hex), "0x%04X", palette[i]);
            f << hex;
            if (i + 1 < 256) f << ", ";
            if ((i + 1) % 8 == 0) f << "\n    ";
        }
        f << "\n};\n";
        f << "static const u8 afn_sky_tex[" << (SKY_W * SKY_H) << "] = {\n    ";
        for (int i = 0; i < SKY_W * SKY_H; i++) {
            unsigned r = rgba[i*4+0] >> 3, g = rgba[i*4+1] >> 3, b = rgba[i*4+2] >> 3;
            uint16_t c15 = (r) | (g << 5) | (b << 10);
            f << (int)nearest[c15];
            if (i + 1 < SKY_W * SKY_H) f << ", ";
            if ((i + 1) % 16 == 0) f << "\n    ";
        }
        f << "\n};\n";
    }

    f << "#endif // MAPDATA_H\n";
    f.close();
    return true;
}

// ---------------------------------------------------------------------------
// PackageNDS entry point
// ---------------------------------------------------------------------------
bool PackageNDS(const std::string& runtimeDir,
                const std::string& outputPath,
                const std::vector<GBASpriteExport>& sprites,
                const std::vector<GBASpriteAssetExport>& assets,
                const GBACameraExport& camera,
                const std::vector<GBAMeshExport>& meshes,
                float orbitDist,
                const std::vector<GBASoundSampleExport>& soundSamples,
                const std::vector<GBASoundInstanceExport>& soundInstances,
                const std::vector<GBASkyFrameExport>& skyFrames,
                bool ndsAntialiasing,
                std::string& errorMsg)
{
    std::string buildOutput;
    std::string msysDir = ToMsysPath(runtimeDir);

    // Step 0: Generate mapdata.h
    if (!GenerateNDSMapData(runtimeDir, sprites, assets, camera, meshes, orbitDist, soundSamples, soundInstances, skyFrames, ndsAntialiasing))
    {
        errorMsg = "Failed to write mapdata.h to " + runtimeDir + "/include/";
        return false;
    }

    // Step 1: Clean
    {
        std::string out;
        std::string cmd = "cd '" + msysDir + "' && make clean 2>&1";
        RunDevkitBash(cmd, out);
        buildOutput += out;
    }

    // Step 2: Build
    {
        std::string out;
        std::string cmd = "cd '" + msysDir + "' && make 2>&1";
        int rc = RunDevkitBash(cmd, out);
        buildOutput += out;

        if (rc != 0)
        {
            errorMsg = "NDS build failed (exit code " + std::to_string(rc) + "):\n\n" + buildOutput;
            return false;
        }
    }

    // Step 3: Verify .nds exists
    fs::path ndsPath = fs::path(runtimeDir) / "affinity.nds";
    if (!fs::exists(ndsPath))
    {
        errorMsg = "Build succeeded but affinity.nds not found.\n\n" + buildOutput;
        return false;
    }

    // Copy to output path if different
    if (fs::path(outputPath) != ndsPath)
    {
        std::error_code ec;
        fs::copy_file(ndsPath, outputPath, fs::copy_options::overwrite_existing, ec);
        if (ec)
        {
            errorMsg = "Build succeeded but failed to copy .nds: " + ec.message() + "\n\n" + buildOutput;
            return false;
        }
    }

    errorMsg = buildOutput;
    return true;
}

} // namespace Affinity
