// Generated by Affinity editor (NDS target)
#ifndef MAPDATA_H
#define MAPDATA_H

#include <nds.h>

// Camera start position (16.8 fixed-point)
#define AFN_CAM_X     32768
#define AFN_CAM_Z     32768
#define AFN_CAM_H     896
#define AFN_CAM_ANGLE 0
#define AFN_CAM_HORIZON 60
#define AFN_WALK_SPEED 37
#define AFN_SPRINT_SPEED 56
#define AFN_WALK_EASE_IN 48
#define AFN_WALK_EASE_OUT 48
#define AFN_SPRINT_EASE_IN 15
#define AFN_SPRINT_EASE_OUT 30

#define AFN_PLAYER_IDX -1
#define AFN_ORBIT_DIST 3840

#define AFN_SPRITE_COUNT 0

#define AFN_MESH_COUNT 0

#endif // MAPDATA_H
