// Generated by Affinity editor
#ifndef MAPDATA_H
#define MAPDATA_H

#define AFFINITY_HAS_SPRITES

// Camera start position
#define AFN_CAM_X     32768
#define AFN_CAM_Z     32768
#define AFN_CAM_H     2560
#define AFN_CAM_ANGLE 0
#define AFN_CAM_HORIZON 50

// Floor sprites from editor
#define AFN_SPRITE_COUNT 0


#endif // MAPDATA_H
