// Generated by Affinity editor — map data for GBA runtime
// This is the default (empty) version. The editor overwrites this file
// with actual tile/palette/tilemap data when packaging.

#ifndef MAPDATA_H
#define MAPDATA_H

// No editor data — runtime will use built-in checkerboard
// Define AFFINITY_HAS_MAPDATA when the editor generates real data

#endif // MAPDATA_H
