// Affinity PSP sprite billboards — GENERATED by Export PSP. Do not edit.
#pragma once

#define AFN_HAS_WORLD_ANCHORS 1
#define AFN_ANCHOR_COUNT 1
// {parent sprite idx, offX, offY, offZ (world px)}
static const float afn_anchors[1][4] = {
  { 6, 0.0f, -0.375f, 0.0f },
};
// (no billboard sprites in this scene)
