// Affinity PSP player collision — GENERATED by Export PSP. Do not edit.
#pragma once

#define AFN_HAS_PLAYER_COL 1
#define AFN_PLAYER_COL_RADIUS (1.2437f)
#define AFN_PLAYER_COL_BOTTOM (0.0000f)
#define AFN_PLAYER_COL_TOP (2.9637f)
