// Affinity PS Vita script (node graph -> C). GENERATED by Export PSV.
#pragma once
#define AFN_HAS_SCRIPT 1

// ---- Generated script code from visual node graph ----
static void afn_emitted_script_init(void)         {
#ifdef AFN_HAS_STICK_SENS
    afn_stick_sens[0] = 8;   // KEY_LSTICK_UP sensitivity 100%
    afn_stick_sens[6] = 8;   // KEY_RSTICK_LEFT sensitivity 100%
    afn_stick_sens[7] = 8;   // KEY_RSTICK_RIGHT sensitivity 100%
    afn_stick_sens[0] = 8;   // KEY_LSTICK_UP sensitivity 100%
    afn_stick_sens[2] = 8;   // KEY_LSTICK_LEFT sensitivity 100%
    afn_stick_sens[3] = 8;   // KEY_LSTICK_RIGHT sensitivity 100%
    afn_stick_sens[5] = 8;   // KEY_RSTICK_DOWN sensitivity 100%
    afn_stick_sens[4] = 8;   // KEY_RSTICK_UP sensitivity 100%
#endif
}
static void afn_emitted_script_start(void) {
}
static void afn_emitted_script_update(void) {
}
static void afn_emitted_script_key_held(void) {
}
static void afn_emitted_script_key_pressed(void) {
}
static void afn_emitted_script_key_released(void) {
}
static void afn_emitted_script_collision(void) {
}
static void afn_emitted_script_collision2d(void) {
}
static void afn_bp0_start(void) {
    afn_play_sound(0);
    afn_tank_camera = 1;
}
static void afn_bp0_update(void) {
}
static void afn_bp0_key_held(void) {
    if (key_is_down(KEY_LSTICK_UP)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[0];
#endif
    if (!afn_player_frozen) afn_input_fwd += afn_key_mag;
    afn_rig_clip = 1;
    if (!afn_speed_prio) afn_move_speed = 10;
    }
    if (key_is_down(KEY_RSTICK_LEFT)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[6];
#endif
    orbit_angle += (250 * afn_key_mag) >> 8;
    }
    if (key_is_down(KEY_RSTICK_RIGHT)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[7];
#endif
    orbit_angle -= (250 * afn_key_mag) >> 8;
    }
    if (key_is_down(KEY_LSTICK_LEFT)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[2];
#endif
    afn_tank_camera = 1;
    afn_player_heading += (500 * afn_key_mag) >> 8;
    }
    if (key_is_down(KEY_LSTICK_RIGHT)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[3];
#endif
    afn_tank_camera = 1;
    afn_player_heading -= (500 * afn_key_mag) >> 8;
    }
    if (key_is_down(KEY_RSTICK_DOWN)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[5];
#endif
    orbit_pitch += (250 * afn_key_mag) >> 8;
    }
    if (key_is_down(KEY_RSTICK_UP)) {
#ifdef AFN_HAS_STICK_SENS
        afn_key_mag = afn_stick_mag[4];
#endif
    orbit_pitch -= (250 * afn_key_mag) >> 8;
    }
}
static void afn_bp0_key_pressed(void) {
    if (key_hit(KEY_START)) {
        afn_key_mag = 256;
    afn_active_camera = 1;
    }
}
static void afn_bp0_key_released(void) {
    if (key_released(KEY_LSTICK_UP)) {
        afn_key_mag = 256;
    afn_rig_clip = 0;
    }
}
static void afn_bp0_collision(void) {
}
static void afn_bp0_collision2d(void) {
}
static void afn_bp1_start(void) {
    afn_gravity = 512;
}
static void afn_bp1_update(void) {
}
static void afn_bp1_key_held(void) {
}
static void afn_bp1_key_pressed(void) {
}
static void afn_bp1_key_released(void) {
}
static void afn_bp1_collision(void) {
}
static void afn_bp1_collision2d(void) {
}

#define AFN_BP_COUNT 2
#define AFN_BP_INSTANCE_COUNT 2
static const unsigned int afn_bp_instances[2][5] = {
    { 0, 0, 4294967295, 0, 0xffffffffu },
    { 1, 6, 4294967295, 0, 0xffffffffu },
};
static void afn_bp_dispatch_start(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_start(); break;
            case 1: afn_bp1_start(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
static void afn_bp_dispatch_update(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_update(); break;
            case 1: afn_bp1_update(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
static void afn_bp_dispatch_key_held(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_key_held(); break;
            case 1: afn_bp1_key_held(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
static void afn_bp_dispatch_key_pressed(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_key_pressed(); break;
            case 1: afn_bp1_key_pressed(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
static void afn_bp_dispatch_key_released(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_key_released(); break;
            case 1: afn_bp1_key_released(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
static void afn_bp_dispatch_collision(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        if (!((int)afn_bp_instances[i][1] == afn_collided_sprite)) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_collision(); break;
            case 1: afn_bp1_collision(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
static void afn_bp_dispatch_collision2d(void) {
    extern int afn_current_mode;
    extern int afn_current_scene;
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) {
        int instMode = (int)afn_bp_instances[i][3];
        if (instMode >= 0 && instMode != afn_current_mode) continue;
        unsigned int mask = afn_bp_instances[i][4];
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue;
        if (!((int)afn_bp_instances[i][2] == afn_collided_tm_obj)) continue;
        int bpIdx = afn_bp_instances[i][0];
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1];
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2];
        switch (bpIdx) {
            case 0: afn_bp0_collision2d(); break;
            case 1: afn_bp1_collision2d(); break;
        }
    }
    afn_bp_cur_spr_idx = -1;
    afn_bp_cur_tm_obj  = -1;
}
