// Affinity PSP script — GENERATED by Export PSP (node graph -> C).
// (Hand-ported from the NDS codegen output for SpyroDemo3a until the PSP
// exporter emits this; same C the NDS runtime runs.)
#pragma once
#include "input.h"        // key_is_down / key_hit / key_released, KEY_*

#define AFN_HAS_SCRIPT 1

// Script runtime variables (defined in script_glue.c).
extern int afn_player_frozen, afn_move_speed, afn_speed_prio, afn_rig_clip;
extern int orbit_angle, afn_current_mode, afn_current_scene;
extern int afn_collided_sprite, afn_collided_tm_obj;
extern int afn_bp_cur_spr_idx, afn_bp_cur_tm_obj;
void afn_play_sound(int smp);

// ---- Generated script code from visual node graph ----
static void afn_emitted_script_init(void)         {}
static void afn_emitted_script_start(void)        {}
static void afn_emitted_script_update(void)       {}
static void afn_emitted_script_key_held(void)     {}
static void afn_emitted_script_key_pressed(void)  {}
static void afn_emitted_script_key_released(void) {}
static void afn_emitted_script_collision(void)    {}
static void afn_emitted_script_collision2d(void)  {}

static void afn_bp0_start(void) { afn_play_sound(0); }
static void afn_bp0_update(void) {}
static void afn_bp0_key_held(void) {
    if (key_is_down(KEY_UP)) {
        if (!afn_player_frozen) afn_input_fwd += 256;
        afn_rig_clip = 1;
        if (!afn_speed_prio) afn_move_speed = 105;
    }
    if (key_is_down(KEY_L)) { orbit_angle += 250; }
    if (key_is_down(KEY_R)) { orbit_angle -= 250; }
}
static void afn_bp0_key_pressed(void) {}
static void afn_bp0_key_released(void) { if (key_released(KEY_UP)) { afn_rig_clip = 0; } }
static void afn_bp0_collision(void) {}
static void afn_bp0_collision2d(void) {}

#define AFN_BP_COUNT 1
#define AFN_BP_INSTANCE_COUNT 1
static const unsigned int afn_bp_instances[1][5] = {
    { 0, 0, 4294967295u, 0, 0xffffffffu },
};

#define AFN_BP_DISPATCH(NAME, CALL, GATE) \
static void NAME(void) { \
    for (int i = 0; i < AFN_BP_INSTANCE_COUNT; i++) { \
        int instMode = (int)afn_bp_instances[i][3]; \
        if (instMode >= 0 && instMode != afn_current_mode) continue; \
        unsigned int mask = afn_bp_instances[i][4]; \
        if (mask != 0xFFFFFFFFu && !(mask & (1u << afn_current_scene))) continue; \
        GATE \
        int bpIdx = afn_bp_instances[i][0]; \
        afn_bp_cur_spr_idx = (int)afn_bp_instances[i][1]; \
        afn_bp_cur_tm_obj  = (int)afn_bp_instances[i][2]; \
        switch (bpIdx) { case 0: CALL(); break; } \
    } \
    afn_bp_cur_spr_idx = -1; afn_bp_cur_tm_obj = -1; \
}
AFN_BP_DISPATCH(afn_bp_dispatch_start,        afn_bp0_start,        )
AFN_BP_DISPATCH(afn_bp_dispatch_update,       afn_bp0_update,       )
AFN_BP_DISPATCH(afn_bp_dispatch_key_held,     afn_bp0_key_held,     )
AFN_BP_DISPATCH(afn_bp_dispatch_key_pressed,  afn_bp0_key_pressed,  )
AFN_BP_DISPATCH(afn_bp_dispatch_key_released, afn_bp0_key_released, )
AFN_BP_DISPATCH(afn_bp_dispatch_collision,    afn_bp0_collision,    if ((int)afn_bp_instances[i][1] != afn_collided_sprite) continue;)
AFN_BP_DISPATCH(afn_bp_dispatch_collision2d,  afn_bp0_collision2d,  if ((int)afn_bp_instances[i][2] != afn_collided_tm_obj) continue;)
#undef AFN_BP_DISPATCH
