// Affinity PSP scene data — PLACEHOLDER (regenerated by "Export PSP").
// A single coloured triangle so a bare build shows something on screen.
#pragma once
#include "affinity_psp.h"

static const AfnVertex afn_mesh0_verts[3] = {
    //  u     v     color (ABGR)   x      y      z
    { 0.0f, 0.0f, 0xff0000ff,  -50.0f, -50.0f, 0.0f },
    { 1.0f, 0.0f, 0xff00ff00,   50.0f, -50.0f, 0.0f },
    { 0.5f, 1.0f, 0xffff0000,    0.0f,  50.0f, 0.0f },
};
static const unsigned short afn_mesh0_idx[3] = { 0, 1, 2 };

const int afn_mesh_count = 1;
const AfnMesh afn_meshes[1] = {
    { 3, 3, afn_mesh0_verts, afn_mesh0_idx, 0, 0, 0, 0, 0, /*cull*/2, /*lit*/0, /*visible*/1 },
};

const int afn_sprite_count = 1;
const AfnSpriteInst afn_sprites[1] = {
    { 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0 },
};

const float afn_cam_start_x = 0.0f;
const float afn_cam_start_z = -200.0f;
const float afn_cam_start_h = 0.0f;
const float afn_cam_start_angle = 0.0f;
const float afn_orbit_dist = 200.0f;
const float afn_draw_distance = 0.0f;
const float afn_walk_speed = 24.0f;
const float afn_sprint_speed = 48.0f;
