// Affinity PSP player collision — GENERATED by Export PSP. Do not edit.
#pragma once

#define AFN_HAS_PLAYER_COL 1
#define AFN_PLAYER_COL_RADIUS (2.6845f)
#define AFN_PLAYER_COL_BOTTOM (-0.1917f)
#define AFN_PLAYER_COL_TOP (6.7113f)
